"use client";

import { CheckCircle2, Download, FileSignature, Landmark, Plus, RefreshCw, ShieldCheck, Upload, Wallet } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { AccountBalance, api, Contract, EscrowAccount, getToken, LedgerTransaction, Payout } from "@/lib/api";

const API_URL=process.env.NEXT_PUBLIC_API_URL??"http://localhost:8000/api/v1";
const brl=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});

export function ContractsModule(){
  const [items,setItems]=useState<Contract[]>([]);const [notice,setNotice]=useState("");const load=()=>api<Contract[]>("/contracts").then(setItems);useEffect(()=>{void load()},[]);
  async function download(c:Contract){const r=await fetch(`${API_URL}/contracts/${c.id}/pdf`,{headers:{Authorization:`Bearer ${getToken()}`}});const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`${c.contract_number}.pdf`;a.click();URL.revokeObjectURL(url)}
  async function sign(c:Contract){try{await api(`/contracts/${c.id}/signature`,{method:"POST",body:JSON.stringify({signer_email:"cliente@exemplo.com.br"})});setNotice("Envelope simulado enviado ao signatário.")}catch(e){setNotice(e instanceof Error?e.message:"Falha na assinatura")}}
  async function upload(e:FormEvent<HTMLFormElement>,c:Contract){e.preventDefault();const input=e.currentTarget.elements.namedItem("file") as HTMLInputElement;if(!input.files?.[0])return;const data=new FormData();data.append("entity_type","contract");data.append("entity_id",c.id);data.append("kind","SUPPORTING_DOCUMENT");data.append("file",input.files[0]);const r=await fetch(`${API_URL}/documents`,{method:"POST",headers:{Authorization:`Bearer ${getToken()}`},body:data});const result=await r.json();setNotice(r.ok?`Documento enviado em quarentena: ${result.filename}`:result.detail)}
  return <ModuleFrame title="Contratos e documentos" subtitle="PDF, integridade, upload em quarentena e assinatura por adaptador." icon={<FileSignature/>}>{notice&&<Notice text={notice}/>}<div className="contract-grid">{items.map(c=><article className="contract-card" key={c.id}><div><FileSignature/><span className={`pill pill-${c.status.toLowerCase()}`}>{c.status}</span></div><b>{c.contract_number}</b><small>Template {c.template_version}</small><code>{c.content_hash.slice(0,24)}...</code><div className="contract-actions"><button onClick={()=>download(c)}><Download/>PDF</button><button onClick={()=>sign(c)}><ShieldCheck/>Assinar</button></div><form onSubmit={e=>upload(e,c)}><input name="file" type="file" accept=".pdf,.png,.jpg,.jpeg,.xml,.docx" required/><button><Upload/>Enviar documento</button></form></article>)}</div></ModuleFrame>
}

export function WalletModule(){
  const [balances,setBalances]=useState<AccountBalance[]>([]);const [txs,setTxs]=useState<LedgerTransaction[]>([]);const load=()=>Promise.all([api<AccountBalance[]>("/ledger/balances"),api<LedgerTransaction[]>("/ledger/transactions")]).then(([b,t])=>{setBalances(b);setTxs(t)});useEffect(()=>{void load()},[]);
  return <ModuleFrame title="Wallet e ledger" subtitle="Saldos derivados do razão contábil de dupla entrada." icon={<Wallet/>}><div className="balance-grid">{balances.map(x=><div className="balance-card" key={x.code}><small>{x.account_type}</small><b>{brl.format(Number(x.balance))}</b><span>{x.name}</span><code>{x.code}</code></div>)}</div><div className="subheading"><h2>Movimentações contábeis</h2><button onClick={load}><RefreshCw/>Atualizar</button></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Referência</th><th>Evento</th><th>Débito</th><th>Crédito</th><th>Valor</th></tr></thead><tbody>{txs.map(x=><tr key={x.id}><td><b>{x.reference}</b><small>{x.description}</small></td><td>{x.event_type}</td><td>{x.debit_account}</td><td>{x.credit_account}</td><td>{brl.format(Number(x.amount))}</td></tr>)}</tbody></table></div></ModuleFrame>
}

export function PaymentsModule(){
  const [accounts,setAccounts]=useState<EscrowAccount[]>([]);const [payouts,setPayouts]=useState<Payout[]>([]);const [notice,setNotice]=useState("");const load=()=>Promise.all([api<EscrowAccount[]>("/escrow/accounts"),api<Payout[]>("/payouts")]).then(([a,p])=>{setAccounts(a);setPayouts(p)});useEffect(()=>{void load()},[]);
  async function createAccount(){await api("/escrow/accounts",{method:"POST",body:"{}"});setNotice("Conta escrow simulada criada.");load()}
  async function deposit(a:EscrowAccount){const event=`evt_dashboard_${Date.now()}`;await api(`/escrow/accounts/${a.id}/mock-webhook`,{method:"POST",body:JSON.stringify({event_id:event,event_type:"FUNDS_CONFIRMED",amount:"10000.00",metadata:{source:"DASHBOARD"}})});setNotice("Webhook idempotente processado: R$ 10.000 confirmados.");load()}
  async function payout(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const fd=new FormData(form);await api("/payouts",{method:"POST",body:JSON.stringify({escrow_account_id:fd.get("escrow_account_id"),beneficiary_name:fd.get("beneficiary_name"),beneficiary_document:fd.get("beneficiary_document"),pix_key:fd.get("pix_key"),amount:fd.get("amount"),condition_evidence:{transfer_confirmed:true,origin:"DASHBOARD"}})});setNotice("Payout bloqueado e enviado para duas aprovações.");form.reset();load()}
  async function approve(p:Payout){try{await api(`/payouts/${p.id}/approve`,{method:"POST",body:JSON.stringify({decision:"APPROVE",comment:"Aprovado pelo painel"})});setNotice("Decisão registrada. São necessários dois revisores diferentes.");load()}catch(e){setNotice(e instanceof Error?e.message:"Falha na aprovação")}}
  return <ModuleFrame title="Pagamentos e escrow" subtitle="Simulação segura de funding, locks e payout com dupla aprovação." icon={<Landmark/>}><div className="toolbar"><button onClick={createAccount}><Plus/>Nova conta escrow</button></div>{notice&&<Notice text={notice}/>}<div className="escrow-grid">{accounts.map(a=><div className="escrow-card" key={a.id}><div><Landmark/><span>{a.provider}</span></div><small>Disponível</small><b>{brl.format(Number(a.available_balance))}</b><small>Bloqueado: {brl.format(Number(a.locked_balance))}</small><button onClick={()=>deposit(a)}>Simular entrada de R$ 10 mil</button></div>)}</div>{accounts.length>0&&<form className="payout-form" onSubmit={payout}><h3>Solicitar payout</h3><select name="escrow_account_id">{accounts.map(a=><option key={a.id} value={a.id}>{a.external_account_id.slice(-10)} · {brl.format(Number(a.available_balance))}</option>)}</select><input name="beneficiary_name" placeholder="Beneficiário" required/><input name="beneficiary_document" placeholder="CPF/CNPJ" required/><input name="pix_key" placeholder="Chave Pix" required/><input name="amount" type="number" min="0.01" step="0.01" placeholder="Valor" required/><button>Solicitar e bloquear</button></form>}<div className="table-wrap"><table className="data-table"><thead><tr><th>Beneficiário</th><th>Valor</th><th>Aprovações</th><th>Status</th><th>Ação</th></tr></thead><tbody>{payouts.map(p=><tr key={p.id}><td><b>{p.beneficiary_name}</b><small>{p.pix_key_masked}</small></td><td>{brl.format(Number(p.amount))}</td><td>{p.approval_count}/2</td><td><span className={`pill pill-${p.status.toLowerCase()}`}>{p.status.replaceAll("_"," ")}</span></td><td><button className="table-action" onClick={()=>approve(p)} disabled={!['PENDING_APPROVAL','PARTIALLY_APPROVED'].includes(p.status)}><CheckCircle2/>Aprovar</button></td></tr>)}</tbody></table></div></ModuleFrame>
}

function ModuleFrame({title,subtitle,icon,children}:{title:string;subtitle:string;icon:React.ReactNode;children:React.ReactNode}){return <><div className="page-heading"><div><span className="eyebrow dark">OPERAÇÃO CONTROLADA</span><h1>{title}</h1><p>{subtitle}</p></div><div className="operational-icon">{icon}</div></div><section className="panel operational-panel financial-panel">{children}</section></>}
function Notice({text}:{text:string}){return <div className="notice"><CheckCircle2/>{text}</div>}
