"use client";
import { Calculator, CheckCircle2, Clock3, ReceiptText, ShieldAlert } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { api, Contract, EarlySettlementQuote, FinOpsDomainEvent, FlashSimulation, PaymentReceipt, getToken } from "@/lib/api";

const API_URL=process.env.NEXT_PUBLIC_API_URL??"http://localhost:8000/api/v1";

const brl=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
export function FinOpsModule(){
 const [simulation,setSimulation]=useState<FlashSimulation|null>(null),[contracts,setContracts]=useState<Contract[]>([]),[quotes,setQuotes]=useState<EarlySettlementQuote[]>([]),[events,setEvents]=useState<FinOpsDomainEvent[]>([]),[receipts,setReceipts]=useState<PaymentReceipt[]>([]),[selectedContract,setSelectedContract]=useState(""),[message,setMessage]=useState("");
 const load=()=>Promise.all([api<Contract[]>("/contracts"),api<EarlySettlementQuote[]>("/early-settlement-quotes"),api<FinOpsDomainEvent[]>("/finops/events")]).then(([c,q,e])=>{setContracts(c);setQuotes(q);setEvents(e)});
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(!selectedContract){setReceipts([]);return}api<PaymentReceipt[]>(`/contracts/${selectedContract}/receipts`).then(setReceipts).catch(()=>setReceipts([]))},[selectedContract]);
 async function downloadReceipt(r:PaymentReceipt){const r2=await fetch(`${API_URL}/contracts/${r.contract_id}/receipts/${r.id}/pdf`,{headers:{Authorization:`Bearer ${getToken()}`}});const blob=await r2.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=r.filename;a.click();URL.revokeObjectURL(url)}
 async function simulate(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{setSimulation(await api<FlashSimulation>("/public/flash-credit/simulate",{method:"POST",body:JSON.stringify({asset_value:f.get("asset_value"),requested_amount:f.get("requested_amount")||null,ipca_projected_percent:f.get("ipca")})}));setMessage("Quatro cenários gerados. Os valores são simulações, sem oferta ou movimentação financeira.")}catch(x){setMessage(x instanceof Error?x.message:"Falha na simulação")}}
 async function quote(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api(`/contracts/${f.get("contract_id")}/early-settlement`,{method:"POST",body:JSON.stringify({current_installment:Number(f.get("installment")),track:f.get("track"),balloon:f.get("balloon")==="on",ipca_projected_percent:f.get("ipca")})});setMessage("Cotação criada com validade de 60 minutos. Pix real permanece bloqueado.");await load()}catch(x){setMessage(x instanceof Error?x.message:"Falha na cotação")}}
 return <><div className="page-heading"><div><span className="eyebrow dark">NINA FINOPS CORE</span><h1>Simulador e quitação</h1><p>Price/IPCA, opção balão, valor presente e eventos financeiros assinados.</p></div><div className="operational-icon"><Calculator/></div></div>{message&&<div className="notice"><CheckCircle2/>{message}</div>}
 <div className="admin-grid"><section className="panel"><h2>Quatro cenários Flash Credit</h2><form className="stack-form" onSubmit={simulate}><input name="asset_value" type="number" min="1" step="0.01" placeholder="AVM do imóvel" defaultValue="1000000" required/><input name="requested_amount" type="number" min="1" step="0.01" placeholder="Valor solicitado (máx. 40%)"/><input name="ipca" type="number" min="0" step="0.01" defaultValue="4.5" required/><button>Simular fundos/pool e linear/balão</button></form></section><section className="panel"><h2>Cotação para contrato ativo</h2><form className="stack-form" onSubmit={quote}><select name="contract_id" required><option value="">Contrato Flash Credit</option>{contracts.map(x=><option key={x.id} value={x.id}>{x.contract_number}</option>)}</select><input name="installment" type="number" min="1" max="36" defaultValue="14" required/><select name="track"><option value="FUNDS">Fundos — 14% a.a.</option><option value="POOL">Pool — 2,5% a.m.</option></select><input name="ipca" type="number" min="0" step="0.01" defaultValue="4.5" required/><label><input name="balloon" type="checkbox"/> Plano com balão no mês 36</label><button>Calcular valor presente</button></form></section></div>
 {simulation&&<section className="panel"><div className="finops-summary"><article><small>Principal</small><strong>{brl.format(Number(simulation.principal))}</strong></article><article><small>LTV</small><strong>{simulation.ltv_percent}%</strong></article><article><small>Cobertura</small><strong>{simulation.coverage_factor}</strong></article><article><small>IPCA projetado</small><strong>{simulation.ipca_projected_percent}%</strong></article>{simulation.platform_fee&&<article><small>Fee plataforma (10%)</small><strong>{brl.format(Number(simulation.platform_fee))}</strong></article>}{simulation.itbi_provision&&<article><small>ITBI (3%)</small><strong>{brl.format(Number(simulation.itbi_provision))}</strong></article>}{simulation.net_payout&&<article><small>Payout líquido</small><strong>{brl.format(Number(simulation.net_payout))}</strong></article>}{simulation.partner_commission_base&&<article><small>Base comissão rede</small><strong>{brl.format(Number(simulation.partner_commission_base))}</strong></article>}</div><div className="scenario-grid">{Object.entries(simulation.scenarios).map(([name,rows])=><article key={name}><b>{name.replaceAll("_"," ")}</b>{[1,12,13,25,36].map(m=>{const r=rows[m-1];return <span key={m}>M{m}: {brl.format(Number(r.installment))}<small>saldo {brl.format(Number(r.settlement_balance))}{r.ipca_adjusted?" · reajuste IPCA":""}</small></span>})}</article>)}</div></section>}
 <section className="panel"><h2><ReceiptText/>Histórico de Faturamentos e Recibos</h2><select value={selectedContract} onChange={e=>setSelectedContract(e.target.value)}><option value="">Selecione o contrato</option>{contracts.map(c=><option key={c.id} value={c.id}>{c.contract_number}</option>)}</select>{receipts.length===0?<small className="form-help">Recibos são emitidos automaticamente na baixa D+0 (webhook BaaS).</small>:<div className="table-wrap"><table className="data-table"><thead><tr><th>Mês</th><th>Fruição</th><th>Amortização</th><th>Total</th><th>Vault S3</th><th>PDF</th></tr></thead><tbody>{receipts.map(r=><tr key={r.id}><td>{r.reference_month}</td><td>{brl.format(Number(r.fruicao_amount))}</td><td>{brl.format(Number(r.amortizacao_amount))}</td><td>{brl.format(Number(r.total_paid))}</td><td><small>{r.vault_s3_uri}</small></td><td><button type="button" onClick={()=>void downloadReceipt(r)}>Baixar</button></td></tr>)}</tbody></table></div>}</section>
 <section className="panel"><h2>Cotações com legal hold</h2><div className="table-wrap"><table className="data-table"><thead><tr><th>Contrato</th><th>Parcela</th><th>Valor presente</th><th>Desconto futuro</th><th>Status</th></tr></thead><tbody>{quotes.map(x=><tr key={x.id}><td><b>{contracts.find(c=>c.id===x.contract_id)?.contract_number??x.contract_id}</b><small>{x.track} · {x.balloon?"balão":"linear"}</small></td><td>{x.installment_number}</td><td>{brl.format(Number(x.settlement_amount))}</td><td>{brl.format(Number(x.future_interest_discount))}</td><td><span className="pill">{x.status}</span><small>expira {new Date(x.expires_at).toLocaleString("pt-BR")}</small></td></tr>)}</tbody></table></div></section>
 <section className="panel"><h2>Eventos FinOps assinados</h2><div className="module-checklist finops-events">{events.map(x=><span key={x.id}>{x.decision.includes("BLOCKED")?<ShieldAlert/>:<Clock3/>}<b>{x.event_type}</b> · {x.decision} · {x.execution_mode}</span>)}</div><small className="form-help">Eventos nunca movimentam fundos, removem patrimônio ou publicam leilão automaticamente.</small></section></>
}
