"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { Building2, KeyRound, Plus, RefreshCw, ShieldCheck, UserPlus, Users } from "lucide-react";
import { api, AuthSession, Branch, Invitation, KycCase, User } from "@/lib/api";

const roles = ["PLATFORM_ADMIN","INTERNAL_STAFF","MASTER_FRANCHISEE","MANAGER","PARTNER","CLIENT","QUOTA_SELLER","RETAIL_INVESTOR","INSTITUTIONAL_FUND","AUDITOR"];
const date = (value:string|null) => value ? new Date(value).toLocaleString("pt-BR") : "—";

export function IdentityModule(){
  const [users,setUsers]=useState<User[]>([]),[branches,setBranches]=useState<Branch[]>([]),[invites,setInvites]=useState<Invitation[]>([]),[message,setMessage]=useState("");
  const load=useCallback(()=>Promise.all([api<User[]>("/admin/users"),api<Branch[]>("/admin/branches"),api<Invitation[]>("/admin/invitations")]).then(([u,b,i])=>{setUsers(u);setBranches(b);setInvites(i)}),[]);
  useEffect(()=>{load().catch(e=>setMessage(e.message))},[load]);
  async function branch(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const f=new FormData(form);await api("/admin/branches",{method:"POST",body:JSON.stringify({name:f.get("name"),code:f.get("code"),region:f.get("region")||null})});form.reset();setMessage("Filial criada.");await load()}
  async function invite(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const f=new FormData(form);const item=await api<Invitation>("/admin/invitations",{method:"POST",body:JSON.stringify({email:f.get("email"),role:f.get("role"),branch_id:f.get("branch_id")||null})});form.reset();setMessage(`Convite criado. Token de desenvolvimento: ${item.token}`);await load()}
  return <><Heading icon={<Users/>} eyebrow="IDENTIDADE E REDE" title="Pessoas, filiais e convites" text="Administração multiunidade com papéis, vínculo regional e ciclo de entrada controlado."/>{message&&<div className="notice"><ShieldCheck/>{message}</div>}<div className="admin-grid"><section className="panel"><h2><Building2/> Nova filial</h2><form className="stack-form" onSubmit={branch}><input name="name" placeholder="Nome da filial" required/><input name="code" placeholder="Código" required/><input name="region" placeholder="Região"/><button><Plus/>Criar filial</button></form></section><section className="panel"><h2><UserPlus/> Convidar usuário</h2><form className="stack-form" onSubmit={invite}><input name="email" type="email" placeholder="E-mail" required/><select name="role">{roles.map(r=><option key={r}>{r}</option>)}</select><select name="branch_id"><option value="">Sem filial</option>{branches.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select><button><UserPlus/>Gerar convite</button></form></section></div><section className="panel identity-table"><div className="panel-title"><h2>Usuários ({users.length})</h2><span>{branches.length} filiais</span></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Usuário</th><th>Papel</th><th>Filial</th><th>MFA</th><th>Último acesso</th><th>Status</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.name}</b><small>{u.email}</small></td><td>{u.role}</td><td>{branches.find(b=>b.id===u.branch_id)?.name??"Matriz"}</td><td><span className={`pill ${u.mfa_enabled?"pill-approved":""}`}>{u.mfa_enabled?"ATIVO":"PENDENTE"}</span></td><td>{date(u.last_login_at)}</td><td>{u.active?"Ativo":"Inativo"}</td></tr>)}</tbody></table></div></section><section className="panel identity-table"><h2>Convites recentes</h2>{invites.map(i=><div className="session-row" key={i.id}><div><b>{i.email}</b><small>{i.role} · expira {date(i.expires_at)}</small></div><span className={`pill pill-${i.status.toLowerCase()}`}>{i.status}</span></div>)}</section></>
}

export function SecurityModule(){
  const [sessions,setSessions]=useState<AuthSession[]>([]),[setup,setSetup]=useState<{secret:string;provisioning_uri:string}|null>(null),[message,setMessage]=useState("");
  const load=useCallback(()=>api<AuthSession[]>("/auth/sessions").then(setSessions),[]);useEffect(()=>{load().catch(e=>setMessage(e.message))},[load]);
  async function revoke(id:string){await api(`/auth/sessions/${id}`,{method:"DELETE"});setMessage("Sessão revogada.");await load()}
  async function beginMfa(){setSetup(await api("/auth/mfa/setup",{method:"POST"}));setMessage("Segredo MFA gerado. Cadastre-o no autenticador e confirme o código.")}
  async function enable(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);await api("/auth/mfa/enable",{method:"POST",body:JSON.stringify({otp:f.get("otp")})});setMessage("MFA ativado com sucesso.");setSetup(null)}
  async function stepUp(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);await api("/auth/step-up",{method:"POST",body:JSON.stringify({password:f.get("password"),otp:f.get("otp")||null})});setMessage("Autenticação reforçada válida por 10 minutos.");await load()}
  return <><Heading icon={<KeyRound/>} eyebrow="SEGURANÇA" title="Sessões e autenticação reforçada" text="MFA TOTP, rotação de refresh token, revogação de sessões e step-up para ações financeiras."/>{message&&<div className="notice"><ShieldCheck/>{message}</div>}<div className="admin-grid"><section className="panel"><h2>MFA TOTP</h2>{!setup?<button className="admin-button" onClick={beginMfa}><KeyRound/>Configurar autenticador</button>:<form className="stack-form" onSubmit={enable}><code className="secret-code">{setup.secret}</code><input name="otp" inputMode="numeric" placeholder="Código de 6 dígitos" required/><button>Confirmar e ativar</button></form>}</section><section className="panel"><h2>Step-up financeiro</h2><form className="stack-form" onSubmit={stepUp}><input name="password" type="password" placeholder="Confirme sua senha" required/><input name="otp" inputMode="numeric" placeholder="MFA, se ativado"/><button><ShieldCheck/>Autorizar por 10 minutos</button></form></section></div><section className="panel identity-table"><div className="panel-title"><h2>Sessões</h2><button onClick={()=>load()}><RefreshCw/>Atualizar</button></div>{sessions.map(s=><div className="session-row" key={s.id}><div><b>{s.user_agent||"Cliente desconhecido"}</b><small>{s.ip_address||"IP indisponível"} · vista {date(s.last_seen_at)} · expira {date(s.expires_at)}</small></div><div className="actions-cell"><span className={`pill ${s.active?"pill-approved":"pill-cancelled"}`}>{s.active?"ATIVA":"REVOGADA"}</span>{s.active&&<button className="table-action" onClick={()=>revoke(s.id)}>Revogar</button>}</div></div>)}</section></>
}

export function ComplianceModule(){
  const [cases,setCases]=useState<KycCase[]>([]),[message,setMessage]=useState("");const load=useCallback(()=>api<KycCase[]>("/kyc/cases").then(setCases),[]);useEffect(()=>{load().catch(e=>setMessage(e.message))},[load]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const f=new FormData(form);await api("/kyc/cases",{method:"POST",body:JSON.stringify({subject_type:f.get("subject_type"),subject_id:f.get("subject_id")})});form.reset();setMessage("Verificação iniciada no provedor simulado.");await load()}
  async function decide(id:string,status:string){await api(`/kyc/cases/${id}/mock-decision`,{method:"POST",body:JSON.stringify({status,risk_level:status==="APPROVED"?"LOW":"HIGH",notes:"Decisão registrada no ambiente de desenvolvimento"})});await load()}
  return <><Heading icon={<ShieldCheck/>} eyebrow="COMPLIANCE" title="Central KYC e KYB" text="Esteira auditável de validação de pessoas e empresas, pronta para troca do adaptador simulado por um fornecedor homologado."/>{message&&<div className="notice"><ShieldCheck/>{message}</div>}<section className="panel"><form className="quick-form kyc-form" onSubmit={create}><select name="subject_type"><option value="PERSON">Pessoa física</option><option value="BUSINESS">Pessoa jurídica</option></select><input name="subject_id" placeholder="ID interno do cliente/empresa" required/><button><Plus/>Iniciar verificação</button></form><div className="table-wrap"><table className="data-table"><thead><tr><th>Objeto</th><th>Provedor</th><th>Risco</th><th>Status</th><th>Revisão</th></tr></thead><tbody>{cases.map(c=><tr key={c.id}><td><b>{c.subject_type}</b><small>{c.subject_id}</small></td><td>{c.provider}</td><td>{c.risk_level||"Pendente"}</td><td><span className={`pill pill-${c.status.toLowerCase()}`}>{c.status}</span></td><td className="actions-cell">{c.status==="PENDING"&&<><button className="table-action" onClick={()=>decide(c.id,"APPROVED")}>Aprovar</button><button className="table-action" onClick={()=>decide(c.id,"REJECTED")}>Rejeitar</button></>}</td></tr>)}</tbody></table></div></section></>
}

function Heading({icon,eyebrow,title,text}:{icon:React.ReactNode;eyebrow:string;title:string;text:string}){return <div className="page-heading"><div><span className="eyebrow dark">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div><div className="operational-icon">{icon}</div></div>}
