"use client";
import { CheckCircle2, ExternalLink, FileCheck2, ShieldCheck, WalletCards } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { api, SaaSPlan, SaaSSubscription, SaaSTerms, ValidStampRecord } from "@/lib/api";
import { ValidStamp } from "@/components/valid-stamp";

const BILLING_OPTIONS = [
  { value: "BOLETO", label: "Boleto bancário" },
  { value: "PIX", label: "Pix (cobrança mensal)" },
  { value: "CREDIT_CARD", label: "Cartão de crédito" },
];

export function LSSModule(){
 const [plans,setPlans]=useState<SaaSPlan[]>([]),[terms,setTerms]=useState<SaaSTerms[]>([]),[subs,setSubs]=useState<SaaSSubscription[]>([]),[stamps,setStamps]=useState<ValidStampRecord[]>([]),[message,setMessage]=useState("");
 const load=()=>Promise.all([api<SaaSPlan[]>("/lss/plans"),api<SaaSTerms[]>("/lss/terms"),api<SaaSSubscription[]>("/lss/subscriptions"),api<ValidStampRecord[]>("/valid-stamps")]).then(([p,t,s,v])=>{setPlans(p);setTerms(t);setSubs(s);setStamps(v)});
 useEffect(()=>{void load()},[]);
 async function subscribe(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);try{const body=await api<SaaSSubscription>("/lss/subscriptions",{method:"POST",body:JSON.stringify({plan_id:f.get("plan_id"),terms_template_id:f.get("terms_id"),company_name:f.get("company_name"),company_cnpj:f.get("company_cnpj"),representative_name:f.get("representative_name"),representative_document:f.get("representative_document"),subscriber_email:f.get("subscriber_email"),billing_type:f.get("billing_type"),scroll_completed:f.get("scroll_completed")==="on",terms_accepted:f.get("terms_accepted")==="on",recurring_authorized:f.get("recurring_authorized")==="on",verification_reference:f.get("verification_reference")})});const checkout=body.payment_checkout_url;if(body.status==="PENDING_PAYMENT"&&checkout){setMessage("Aceite registrado. Conclua o pagamento da primeira mensalidade para ativar o LSS.");window.open(checkout,"_blank","noopener,noreferrer")}else if(body.status==="ACTIVE_SANDBOX"){setMessage("Aceite LSS registrado em sandbox — cobrança real indisponível neste ambiente.")}else{setMessage("Assinatura LSS criada no Asaas. Aguarde a confirmação do pagamento.")}form.reset();await load()}catch(x){setMessage(x instanceof Error?x.message:"Falha no aceite")}}
 async function cancel(id:string){try{await api(`/lss/subscriptions/${id}/cancel`,{method:"POST",body:"{}"});setMessage("Cancelamento agendado para o fim do período, sem perda imediata de acesso.");await load()}catch(x){setMessage(x instanceof Error?x.message:"Falha ao cancelar")}}
 const activeTerms=terms.find(x=>x.active&&x.legal_review_status==="APPROVED"),plan=plans[0];
 const hasLiveBilling=subs.some(x=>x.asaas_subscription_id)||subs.some(x=>x.status==="PENDING_PAYMENT");
 return <><div className="page-heading"><div><span className="eyebrow dark">LETTER SERVICING SUITE</span><h1>SaaS LSS</h1><p>Contrato clickwrap versionado, recorrência mensal via Asaas e trilha de aceite.</p></div><div className="operational-icon"><FileCheck2/></div></div>{message&&<div className="notice"><ShieldCheck/>{message}</div>}
 <div className="lss-grid"><section className="panel lss-offer"><span className="eyebrow dark">PLANO EMPRESARIAL</span><h2>{plan?.name??"LSS Profissional"}</h2><strong>R$ {Number(plan?.monthly_price??199.9).toLocaleString("pt-BR",{minimumFractionDigits:2})}<small>/mês</small></strong><ul><li><CheckCircle2/>Aceite com IP, data, hash e verificação</li><li><CheckCircle2/>Cobrança recorrente parametrizada no Asaas</li><li><CheckCircle2/>Cancelamento ao final do período</li></ul>{!hasLiveBilling&&<div className="warning-banner"><WalletCards/><div><strong>Ambiente sem Asaas</strong><p>Sem API Key configurada, o aceite permanece em sandbox sem cobrança real.</p></div></div>}</section>
 <section className="panel"><h2>Contratar como Pessoa Jurídica</h2><form className="stack-form" onSubmit={subscribe}><select name="plan_id" required defaultValue=""><option value="" disabled>Selecione o plano</option>{plans.map(x=><option key={x.id} value={x.id}>{x.name} · R$ {x.monthly_price}</option>)}</select><select name="terms_id" required defaultValue=""><option value="" disabled>Termos aprovados</option>{terms.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.title} v{x.version}</option>)}</select><input name="company_name" placeholder="Razão social" required/><input name="company_cnpj" placeholder="CNPJ" required/><input name="representative_name" placeholder="Representante legal" required/><input name="representative_document" placeholder="CPF do representante" required/><input name="subscriber_email" type="email" placeholder="E-mail financeiro" required/><select name="billing_type" required defaultValue="BOLETO">{BILLING_OPTIONS.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select><input name="verification_reference" placeholder="Referência OTP/liveness" required/><label><input type="checkbox" name="scroll_completed" required/> Li integralmente os termos v{activeTerms?.version??"—"}</label><label><input type="checkbox" name="terms_accepted" required/> Aceito o contrato SaaS</label><label><input type="checkbox" name="recurring_authorized" required/> Autorizo cobrança recorrente mensal</label><button>Contratar LSS</button></form></section></div>
 <section className="panel"><h2>Assinaturas e evidências</h2><div className="contract-grid">{subs.map(x=><article className="contract-card" key={x.id}><b>{x.subscriber_company_name}</b><span className={`pill pill-${x.status.toLowerCase().replace(/_/g,"-")}`}>{x.status}</span><code>{x.acceptance_hash}</code><small>Acesso até {new Date(x.current_period_end).toLocaleDateString("pt-BR")}</small>{x.billing_type&&<small>Forma: {x.billing_type}{x.last_payment_status?` · ${x.last_payment_status}`:""}</small>}{x.payment_checkout_url&&x.status==="PENDING_PAYMENT"&&<a className="table-action" href={x.payment_checkout_url} target="_blank" rel="noopener noreferrer"><ExternalLink/> Pagar mensalidade</a>}{!x.cancel_at_period_end&&<button className="table-action" onClick={()=>cancel(x.id)}>Cancelar no fim do período</button>}{stamps.find(s=>s.entity_id===x.id)&&<ValidStamp code={stamps.find(s=>s.entity_id===x.id)!.stamp_code} hash={stamps.find(s=>s.entity_id===x.id)!.chain_hash}/>}</article>)}</div></section></>
}
