"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { BrainCircuit, CheckCircle2, Download, Gauge, ShieldCheck, Sparkles } from "lucide-react";
import { api, BISummary, downloadApi, Proposal, UnderwritingAssessment, UnderwritingPolicy } from "@/lib/api";

const brl=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});

export function NinaModule(){
  const [policies,setPolicies]=useState<UnderwritingPolicy[]>([]),[assessments,setAssessments]=useState<UnderwritingAssessment[]>([]),[proposals,setProposals]=useState<Proposal[]>([]),[ranking,setRanking]=useState<{quota_ids:string[];total_credit:string;deviation_percent:string;score:number;explanation:string}[]>([]),[message,setMessage]=useState("");
  const load=useCallback(()=>Promise.all([api<UnderwritingPolicy[]>("/nina/policies"),api<UnderwritingAssessment[]>("/nina/assessments"),api<Proposal[]>("/proposals")]).then(([p,a,r])=>{setPolicies(p);setAssessments(a);setProposals(r)}),[]);useEffect(()=>{load().catch(e=>setMessage(e.message))},[load]);
  async function policy(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await api("/nina/policies",{method:"POST",body:JSON.stringify({product:f.get("product"),minimum_score:f.get("minimum_score"),manual_review_score:f.get("manual_review_score"),maximum_ltv_percent:f.get("maximum_ltv_percent"),maximum_commitment_percent:f.get("maximum_commitment_percent"),rules:{engine:"deterministic-v1"}})});setMessage("Nova política de underwriting ativada.");await load()}
  async function assess(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await api(`/nina/proposals/${f.get("proposal_id")}/assess`,{method:"POST",body:JSON.stringify({policy_id:f.get("policy_id"),monthly_income:f.get("monthly_income"),monthly_commitment:f.get("monthly_commitment"),asset_value:f.get("asset_value"),external_score:f.get("external_score"),document_completeness_percent:f.get("document_completeness_percent"),kyc_status:f.get("kyc_status")})});setMessage("Score calculado com memória explicável.");await load()}
  async function rank(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const rows=await api<typeof ranking>(`/nina/quota-ranking?target_amount=${f.get("target")}&category=${f.get("category")}`);setRanking(rows);setMessage(`${rows.length} combinações ranqueadas.`)}
  return <><Heading title="NINA Advanced Underwriting" text="Políticas versionadas, score explicável, decisão humana e ranking de combinações." icon={<BrainCircuit/>}/>{message&&<Notice text={message}/>}<Metrics items={[["Políticas",policies.length],["Avaliações",assessments.length],["Risco alto",assessments.filter(x=>x.risk_band==="HIGH").length],["Decisão pendente",assessments.filter(x=>x.status==="PENDING_DECISION").length]]}/><div className="nina-grid"><section className="panel"><h2><Gauge/>Política de risco</h2><form className="stack-form" onSubmit={policy}><select name="product"><option>MARKETPLACE</option><option>SDC</option><option>FLASH_CREDIT</option></select><input name="minimum_score" type="number" defaultValue="650" required/><input name="manual_review_score" type="number" defaultValue="720" required/><input name="maximum_ltv_percent" type="number" defaultValue="40" required/><input name="maximum_commitment_percent" type="number" defaultValue="35" required/><button>Criar nova versão</button></form></section><section className="panel"><h2><Sparkles/>Executar avaliação</h2><form className="stack-form" onSubmit={assess}><select name="proposal_id">{proposals.map(x=><option value={x.id} key={x.id}>{x.product} · {brl.format(Number(x.requested_amount))}</option>)}</select><select name="policy_id">{policies.filter(x=>x.active).map(x=><option value={x.id} key={x.id}>{x.product} v{x.version}</option>)}</select><input name="monthly_income" type="number" placeholder="Renda mensal" required/><input name="monthly_commitment" type="number" placeholder="Comprometimento atual" required/><input name="asset_value" type="number" placeholder="Valor do ativo" required/><input name="external_score" type="number" placeholder="Score externo 0-1000" required/><input name="document_completeness_percent" type="number" defaultValue="100" required/><select name="kyc_status"><option>APPROVED</option><option>PENDING</option><option>REJECTED</option></select><button>Calcular score</button></form></section></div><section className="panel identity-table"><h2>Fila de underwriting</h2>{assessments.map(x=><div className="session-row" key={x.id}><div><b>Score {x.score} · risco {x.risk_band}</b><small>{x.recommendation} · {(x.explanation.summary as string)||"Memória explicável disponível"}</small></div><span className={`pill pill-${x.status.toLowerCase()}`}>{x.status}</span></div>)}</section><section className="panel ranking-panel"><h2>Ranking de combinações</h2><form className="quick-form" onSubmit={rank}><input name="target" type="number" placeholder="Crédito alvo" required/><select name="category"><option>REAL_ESTATE</option><option>VEHICLE</option></select><button>Ranquear</button></form>{ranking.map((x,i)=><div className="compact-row" key={x.quota_ids.join()}><span><b>#{i+1} · score {x.score}</b><small>{x.explanation}</small></span><strong>{brl.format(Number(x.total_credit))}</strong></div>)}</section></>
}

export function BIModule(){const [data,setData]=useState<BISummary|null>(null),[message,setMessage]=useState("");useEffect(()=>{api<BISummary>("/bi/summary").then(setData).catch(e=>setMessage(e.message))},[]);return <><Heading title="BI executivo LETTER" text="Funil, carteira, risco, funding e recuperação em uma visão consolidada." icon={<Gauge/>}/>{message&&<Notice text={message}/>} {data&&<><div className="bi-kpis"><Kpi label="Leads" value={data.funnel.leads}/><Kpi label="Propostas" value={data.funnel.proposals}/><Kpi label="Carteira aberta" value={brl.format(Number(data.portfolio.open))}/><Kpi label="Recebido" value={brl.format(Number(data.portfolio.paid))}/><Kpi label="Risco alto" value={data.risk.high_risk}/><Kpi label="Decisões pendentes" value={data.risk.pending_decisions}/><Kpi label="Funding confirmado" value={brl.format(Number(data.funding.funded))}/><Kpi label="Recuperado" value={brl.format(Number(data.recovery.settled))}/></div><section className="panel executive-report"><div><h2>Relatório executivo</h2><p>Exportação UTF-8 pronta para Excel com todos os indicadores consolidados.</p></div><button onClick={()=>downloadApi("/bi/executive-report.csv","letter-executive-report.csv")}><Download/>Exportar CSV</button></section></>}</>}

function Heading({title,text,icon}:{title:string;text:string;icon:React.ReactNode}){return <div className="page-heading"><div><span className="eyebrow dark">INTELIGÊNCIA LETTER</span><h1>{title}</h1><p>{text}</p></div><div className="operational-icon">{icon}</div></div>}
function Notice({text}:{text:string}){return <div className="notice"><ShieldCheck/>{text}</div>}
function Metrics({items}:{items:[string,string|number][]}){return <div className="network-metrics">{items.map(([l,v])=><article key={l}><small>{l}</small><strong>{v}</strong></article>)}</div>}
function Kpi({label,value}:{label:string;value:string|number}){return <article><CheckCircle2/><small>{label}</small><strong>{value}</strong></article>}
