"use client";

import { Check, Clock3, FileText, LockKeyhole, Plus, RefreshCw, Unlock, Users, WalletCards } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { Administrator, api, Calculation, Contract, Lead, Proposal, Quota, Reservation } from "@/lib/api";
import { FLASH_CAPITAL_SOURCES, productLabel, SDC_CAPITAL_SOURCES } from "@/lib/products";
import { SdcQuitConProjectionTable } from "@/components/sdc-quitcon-card";

const brl = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });

export function LeadsModule() {
  const [items,setItems]=useState<Lead[]>([]); const [error,setError]=useState("");
  const load=()=>api<Lead[]>("/leads").then(setItems).catch(e=>setError(e.message));
  useEffect(()=>{void load()},[]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const fd=new FormData(form);await api("/leads",{method:"POST",body:JSON.stringify({name:fd.get("name"),phone:fd.get("phone"),product_interest:fd.get("product_interest"),source:"DASHBOARD"})});form.reset();load()}
  async function advance(lead:Lead){const next:Record<string,string>={NEW:"CONTACTED",CONTACTED:"QUALIFIED",QUALIFIED:"PROPOSAL",PROPOSAL:"CONVERTED"};await api(`/leads/${lead.id}`,{method:"PATCH",body:JSON.stringify({status:next[lead.status]??"QUALIFIED"})});load()}
  return <OperationalLayout title="CRM e originação" subtitle="Cadastre leads e avance a jornada comercial com histórico auditável." icon={<Users/>}>
    <form className="quick-form" onSubmit={submit}><input name="name" placeholder="Nome do cliente" required minLength={2}/><input name="phone" placeholder="WhatsApp" required minLength={8}/><select name="product_interest"><option value="MARKETPLACE">Marketplace</option><option value="SDC">SDC</option><option value="FLASH_CREDIT">Flash Capital</option></select><button><Plus/>Adicionar lead</button></form>
    {error&&<div className="error">{error}</div>}<DataTable headers={["Cliente","Contato","Interesse","Status","Ação"]}>{items.map(x=><tr key={x.id}><td><b>{x.name}</b><small>{x.source}</small></td><td>{x.phone}</td><td>{productLabel(x.product_interest)}</td><td><Pill value={x.status}/></td><td><button className="table-action" onClick={()=>advance(x)}>Avançar</button></td></tr>)}</DataTable>
  </OperationalLayout>
}

export function InventoryModule() {
  const [items,setItems]=useState<Quota[]>([]);const [admins,setAdmins]=useState<Administrator[]>([]);const [reservations,setReservations]=useState<Reservation[]>([]);const [error,setError]=useState("");
  const load=()=>Promise.all([api<Quota[]>("/quotas"),api<Administrator[]>("/administrators"),api<Reservation[]>("/reservations")]).then(([q,a,r])=>{setItems(q);setAdmins(a);setReservations(r)}).catch(e=>setError(e.message));useEffect(()=>{void load()},[]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const fd=new FormData(form);await api("/quotas",{method:"POST",body:JSON.stringify({administrator_id:fd.get("administrator_id"),group_code:fd.get("group_code"),quota_code:fd.get("quota_code"),category:fd.get("category"),credit_value:fd.get("credit_value"),outstanding_balance:fd.get("outstanding_balance")||"0",premium_value:fd.get("premium_value")||"0"})});form.reset();load()}
  async function reserve(quota:Quota){setError("");try{await api("/reservations",{method:"POST",body:JSON.stringify({quota_id:quota.id,ttl_minutes:30})});load()}catch(e){setError(e instanceof Error?e.message:"Falha na reserva")}}
  async function release(quota:Quota){const res=reservations.find(r=>r.quota_id===quota.id&&r.status==="ACTIVE");if(res){await api(`/reservations/${res.id}/release`,{method:"POST"});load()}}
  return <OperationalLayout title="Cotas e inventário" subtitle="Gerencie estoque, valores e locks contra dupla venda." icon={<WalletCards/>}>
    <form className="quick-form quota-form" onSubmit={submit}><select name="administrator_id" required>{admins.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><input name="group_code" placeholder="Grupo" required/><input name="quota_code" placeholder="Cota" required/><select name="category"><option value="REAL_ESTATE">Imóvel</option><option value="VEHICLE">Veículo</option></select><input name="credit_value" type="number" min="1" step="0.01" placeholder="Crédito" required/><input name="premium_value" type="number" min="0" step="0.01" placeholder="Ágio"/><input name="outstanding_balance" type="number" min="0" step="0.01" placeholder="Saldo devedor"/><button><Plus/>Cadastrar cota</button></form>
    {error&&<div className="error">{error}</div>}<DataTable headers={["Identificação","Categoria","Crédito","Ágio","Status","Reserva"]}>{items.map(x=><tr key={x.id}><td><b>Grupo {x.group_code}</b><small>Cota {x.quota_code}</small></td><td>{x.category==="REAL_ESTATE"?"Imóvel":"Veículo"}</td><td>{brl.format(Number(x.credit_value))}</td><td>{brl.format(Number(x.premium_value))}</td><td><Pill value={x.status}/></td><td>{x.status==="AVAILABLE"?<button className="table-action lock" onClick={()=>reserve(x)}><LockKeyhole/>Reservar 30 min</button>:x.status==="RESERVED"?<button className="table-action" onClick={()=>release(x)}><Unlock/>Liberar</button>:"—"}</td></tr>)}</DataTable>
  </OperationalLayout>
}

export function ProposalsModule() {
  const [items,setItems]=useState<Proposal[]>([]);const [leads,setLeads]=useState<Lead[]>([]);const [quotas,setQuotas]=useState<Quota[]>([]);const [contracts,setContracts]=useState<Contract[]>([]);const [selected,setSelected]=useState<string[]>([]);const [notice,setNotice]=useState("");
  const [duration,setDuration]=useState(12);const [sdcCapitalSource,setSdcCapitalSource]=useState("POOL");const [poolInvestmentAmount,setPoolInvestmentAmount]=useState("80000");const [sdcPoolInvestorRate,setSdcPoolInvestorRate]=useState("");const [assetValue,setAssetValue]=useState("500000");const [capitalSource,setCapitalSource]=useState("RETAIL");const [flashPoolInvestorRate,setFlashPoolInvestorRate]=useState("");const [term,setTerm]=useState(36);const [ipca,setIpca]=useState("4.5");const [lastCalculation,setLastCalculation]=useState<Calculation|null>(null);
  const poolTierPreview=useMemo(()=>{const amount=Number(poolInvestmentAmount);if(!amount||amount<=0)return null;return amount<=100000?{rate:"1,6",label:"Até R$ 100.000,00"}:{rate:"2,0",label:"A partir de R$ 100.000,00"}},[poolInvestmentAmount]);
  const load=()=>Promise.all([api<Proposal[]>("/proposals"),api<Lead[]>("/leads"),api<Quota[]>("/quotas"),api<Contract[]>("/contracts")]).then(([p,l,q,c])=>{setItems(p);setLeads(l);setQuotas(q);setContracts(c)});useEffect(()=>{void load()},[]);
  const available=useMemo(()=>quotas.filter(q=>q.status==="AVAILABLE"),[quotas]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const fd=new FormData(form);await api("/proposals",{method:"POST",body:JSON.stringify({lead_id:fd.get("lead_id"),product:fd.get("product"),requested_amount:fd.get("requested_amount"),terms:{channel:"DASHBOARD"}})});form.reset();load()}
  async function calculate(p:Proposal){setNotice("");try{let path=`/proposals/${p.id}/calculate`;let payload:Record<string,unknown>={quota_ids:selected,fee_percent:"10",start_fee:"1500"};if(p.product==="SDC"){path=`/proposals/${p.id}/calculate-sdc`;payload={quota_ids:selected,duration_months:duration,capital_source:sdcCapitalSource};if(sdcCapitalSource==="POOL"){if(poolInvestmentAmount)payload.pool_investment_amount=poolInvestmentAmount;if(sdcPoolInvestorRate)payload.pool_investor_rate_percent=sdcPoolInvestorRate}}if(p.product==="FLASH_CREDIT"){path=`/proposals/${p.id}/calculate-flash-credit`;payload={asset_value:assetValue,capital_source:capitalSource,term_months:term,ipca_annual_percent:ipca};if(capitalSource==="RETAIL"){if(poolInvestmentAmount)payload.pool_investment_amount=poolInvestmentAmount;if(flashPoolInvestorRate)payload.pool_investor_rate_percent=flashPoolInvestorRate}}const calc=await api<Calculation>(path,{method:"POST",body:JSON.stringify(payload)});setLastCalculation(calc);setNotice(`Memória ${calc.formula_version} criada com sucesso.`);setSelected([]);load()}catch(e){setNotice(e instanceof Error?e.message:"Falha no cálculo")}}
  async function contract(p:Proposal){const calcs=await api<{id:string}[]>(`/proposals/${p.id}/calculations`);if(!calcs.length){setNotice("Calcule a proposta antes de gerar o contrato.");return}await api(`/proposals/${p.id}/contracts`,{method:"POST",body:JSON.stringify({calculation_memory_id:calcs[0].id})});setNotice("Contrato gerado com hash de integridade.");load()}
  return <OperationalLayout title="Propostas e simulações" subtitle="Crie propostas, selecione cotas e gere memória de cálculo versionada." icon={<FileText/>}>
    <form className="quick-form" onSubmit={submit}><select name="lead_id" required>{leads.map(l=><option value={l.id} key={l.id}>{l.name}</option>)}</select><select name="product"><option value="MARKETPLACE">Marketplace</option><option value="SDC">SDC</option><option value="FLASH_CREDIT">Flash Capital</option></select><input name="requested_amount" type="number" min="1" step="0.01" placeholder="Valor solicitado" required/><button><Plus/>Nova proposta</button></form>
    <div className="product-parameters"><div><b>Parâmetros documentais</b><small>Taxas totais travadas (SDC 4,5% / Flash 2,5%). Rentabilidade pool por faixa de aplicação — livre de imposto.</small></div><label>SDC — duração<input type="number" min="1" max="60" value={duration} onChange={e=>setDuration(Number(e.target.value))}/></label><label>SDC — origem<select value={sdcCapitalSource} onChange={e=>setSdcCapitalSource(e.target.value)}>{SDC_CAPITAL_SOURCES.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label>{sdcCapitalSource==="POOL"&&<><label>Pool — valor aplicado (R$)<input type="number" min="1" step="0.01" value={poolInvestmentAmount} onChange={e=>setPoolInvestmentAmount(e.target.value)}/><small>Até R$ 100 mil: 1,6% a.m. · A partir de R$ 100 mil: 2,0% a.m.</small></label>{poolTierPreview&&<div className="notice"><RefreshCw/>Faixa: {poolTierPreview.label} → {poolTierPreview.rate}% a.m. (livre de imposto)</div>}<label>SDC — override campanha (% a.m., opcional)<input type="number" min="0" max="4.5" step="0.1" value={sdcPoolInvestorRate} onChange={e=>setSdcPoolInvestorRate(e.target.value)} placeholder="Deixe vazio para faixa automática"/></label></>}<label>Valor do bem<input type="number" min="1" value={assetValue} onChange={e=>setAssetValue(e.target.value)}/></label><label>Flash Capital — origem<select value={capitalSource} onChange={e=>setCapitalSource(e.target.value)}>{FLASH_CAPITAL_SOURCES.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label>{capitalSource==="RETAIL"&&<><label>Pool — valor aplicado (R$)<input type="number" min="1" step="0.01" value={poolInvestmentAmount} onChange={e=>setPoolInvestmentAmount(e.target.value)}/><small>Até R$ 100 mil: 1,6% a.m. · A partir de R$ 100 mil: 2,0% a.m.</small></label>{poolTierPreview&&<div className="notice"><RefreshCw/>Faixa: {poolTierPreview.label} → {poolTierPreview.rate}% a.m. (livre de imposto)</div>}<label>Flash — override campanha (% a.m., opcional)<input type="number" min="0" max="2.5" step="0.1" value={flashPoolInvestorRate} onChange={e=>setFlashPoolInvestorRate(e.target.value)} placeholder="Deixe vazio para faixa automática"/></label></>}<label>Prazo<select value={term} onChange={e=>setTerm(Number(e.target.value))}><option value={36}>36 meses</option><option value={60}>60 meses + balão</option></select></label><label>IPCA a.a.<input type="number" min="0" step="0.01" value={ipca} onChange={e=>setIpca(e.target.value)}/></label></div>
    <div className="selection-box"><div><b>Cotas para Marketplace/SDC</b><small>Selecione cotas da mesma administradora e categoria. Tolerância: ±10%.</small></div><div>{available.map(q=><label key={q.id}><input type="checkbox" checked={selected.includes(q.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,q.id]:v.filter(id=>id!==q.id))}/>{q.group_code}/{q.quota_code} · {q.category==="REAL_ESTATE"?"Imóvel":"Veículo"} · {brl.format(Number(q.credit_value))}</label>)}</div></div>
    {notice&&<div className="notice"><RefreshCw/>{notice}</div>}{lastCalculation&&<CalculationResult calculation={lastCalculation}/>}<DataTable headers={["Produto","Valor","Versão","Status","Workflow"]}>{items.map(p=>{const hasContract=contracts.some(c=>c.proposal_id===p.id);const needsQuota=p.product!=="FLASH_CREDIT";return <tr key={p.id}><td><b>{productLabel(p.product)}</b><small>{leads.find(l=>l.id===p.lead_id)?.name}</small></td><td>{brl.format(Number(p.requested_amount))}</td><td>{p.calculation_version}</td><td><Pill value={p.status}/></td><td className="actions-cell"><button className="table-action" disabled={needsQuota&&!selected.length} onClick={()=>calculate(p)}>Simular</button><button className="table-action" disabled={hasContract} onClick={()=>contract(p)}>{hasContract?"Contrato criado":"Gerar contrato"}</button></td></tr>})}</DataTable>
  </OperationalLayout>
}

function CalculationResult({calculation}:{calculation:Calculation}){const labels:Record<string,string>={principal:"Principal (nominal)",total_interest:"Juros totais",investor_interest:"Investidores",platform_spread:"Spread LETTER",maturity_total:"Total no vencimento",start_fee_total:"Taxa de Start",start_fee_milestone_1:"Marco 1",start_fee_milestone_2:"Marco 2",intermediation_fee:"Fee 10%",capital_commission:"Captação 1%",asset_value:"Valor do bem",ltv_percent:"LTV (%)",monthly_payment:"Parcela",balloon_payment:"Parcela balão",management_fee_total:"Gestão 0,5%",itbi_provision:"Provisão ITBI",platform_fee:"Fee plataforma",structuring_fee:"Fee plataforma",partner_commission_base:"Base comissão rede",net_payout:"Payout líquido",total_contract:"Total do contrato",pool_investor_rate_percent:"Rentabilidade pool (% a.m.)",pool_investor_tier_label:"Faixa pool",pool_investor_tax_status:"Status fiscal pool",investor_rate_percent:"Rentabilidade investidor (% a.m.)",platform_spread_rate_percent:"Spread plataforma (% a.m.)"};const entries=Object.entries(calculation.output).filter(([key,value])=>labels[key]&&value!==null);const notes=[calculation.output.partner_commission_basis_note,calculation.output.interest_basis_note,calculation.output.pool_investor_tax_note].filter(x=>typeof x==="string");const quitconContext=calculation.formula_version.startsWith("sdc-")&&calculation.quitcon_sdc?{proposalId:calculation.proposal_id,calculationMemoryId:calculation.id,mesesRestantes:Number(calculation.output.duration_months??calculation.input.duration_months??0)||undefined}:undefined;return <div className="calculation-result"><div><span className="eyebrow dark">MEMÓRIA VERSIONADA</span><b>{calculation.formula_version}</b></div>{notes.map((note,i)=><small key={i}>{String(note)}</small>)}<div>{entries.map(([key,value])=><article key={key}><small>{labels[key]}</small><strong>{key.includes("percent")||key==="pool_investor_rate_percent"?`${value}%`:key==="pool_investor_tax_status"?"Livre de imposto (sem retenção)":key.includes("tier")?String(value):brl.format(Number(value))}</strong></article>)}</div>{calculation.quitcon_sdc&&<SdcQuitConProjectionTable data={calculation.quitcon_sdc} context={quitconContext}/>}</div>}

function OperationalLayout({title,subtitle,icon,children}:{title:string;subtitle:string;icon:React.ReactNode;children:React.ReactNode}){return <><div className="page-heading"><div><span className="eyebrow dark">OPERAÇÃO ATIVA</span><h1>{title}</h1><p>{subtitle}</p></div><div className="operational-icon">{icon}</div></div><section className="panel operational-panel">{children}</section></>}
function DataTable({headers,children}:{headers:string[];children:React.ReactNode}){return <div className="table-wrap"><table className="data-table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function Pill({value}:{value:string}){return <span className={`pill pill-${value.toLowerCase()}`}>{value.replaceAll("_"," ")}</span>}
