"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { Activity, CheckCircle2, Database, Play, RefreshCw, ShieldCheck, Webhook } from "lucide-react";
import { AdapterCatalogItem, AdapterCertification, AdapterExecution, api, apiForm, GoLiveApproval, GoLiveDecision, HomologationEvidence, OnboardingProfile, OperationalJob, ProviderIncident, ProviderIntegration, ProviderReconciliationRun, WebhookDelivery, WebhookEndpoint } from "@/lib/api";

function Metric({label,value}:{label:string;value:string|number}){return <div className="metric"><span>{label}</span><b>{value}</b></div>}

export function OperationsModule(){
  const [jobs,setJobs]=useState<OperationalJob[]>([]);
  const [metrics,setMetrics]=useState<Record<string,number>>({});
  const [ready,setReady]=useState<Record<string,string>>({});
  const [homologation,setHomologation]=useState<{status:string;blocking_issues:string[];external_providers:Record<string,string>}|null>(null);
  const [integrations,setIntegrations]=useState<ProviderIntegration[]>([]);
  const [endpoints,setEndpoints]=useState<WebhookEndpoint[]>([]);
  const [deliveries,setDeliveries]=useState<WebhookDelivery[]>([]);
  const [incidents,setIncidents]=useState<ProviderIncident[]>([]);
  const [profiles,setProfiles]=useState<OnboardingProfile[]>([]);
  const [reconciliations,setReconciliations]=useState<ProviderReconciliationRun[]>([]);
  const [evidences,setEvidences]=useState<HomologationEvidence[]>([]);
  const [adapterCatalog,setAdapterCatalog]=useState<AdapterCatalogItem[]>([]);
  const [adapterExecutions,setAdapterExecutions]=useState<AdapterExecution[]>([]);
  const [certifications,setCertifications]=useState<AdapterCertification[]>([]);
  const [goLiveApprovals,setGoLiveApprovals]=useState<GoLiveApproval[]>([]);
  const [goLiveDecisions,setGoLiveDecisions]=useState<GoLiveDecision[]>([]);
  const [message,setMessage]=useState("");

  const load=useCallback(()=>Promise.all([
    api<OperationalJob[]>("/system/jobs"),api<Record<string,number>>("/system/metrics"),
    api<Record<string,string>>("/system/readiness"),api<{status:string;blocking_issues:string[];external_providers:Record<string,string>}>("/system/homologation"),
    api<ProviderIntegration[]>("/system/integrations"),api<WebhookEndpoint[]>("/system/webhook-endpoints"),api<WebhookDelivery[]>("/system/webhook-deliveries"),api<ProviderIncident[]>("/system/provider-incidents"),
    api<OnboardingProfile[]>("/system/onboarding-profiles"),api<ProviderReconciliationRun[]>("/system/reconciliation-runs"),api<HomologationEvidence[]>("/system/homologation-evidences"),
    api<AdapterCatalogItem[]>("/system/adapter-catalog"),api<AdapterExecution[]>("/system/adapter-executions"),api<AdapterCertification[]>("/system/adapter-certifications"),
    api<GoLiveApproval[]>("/system/go-live-approvals"),api<GoLiveDecision[]>("/system/go-live-decisions")
  ]).then(([j,m,r,h,i,e,d,n,p,c,v,a,x,ct,ga,gd])=>{setJobs(j);setMetrics(m);setReady(r);setHomologation(h);setIntegrations(i);setEndpoints(e);setDeliveries(d);setIncidents(n);setProfiles(p);setReconciliations(c);setEvidences(v);setAdapterCatalog(a);setAdapterExecutions(x);setCertifications(ct);setGoLiveApprovals(ga);setGoLiveDecisions(gd)}),[]);
  useEffect(()=>{load().catch(e=>setMessage(e.message))},[load]);

  async function createJob(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await api("/system/jobs",{method:"POST",body:JSON.stringify({job_type:f.get("job_type"),idempotency_key:`ui-job-${Date.now()}`,payload:{source:"dashboard"},max_attempts:f.get("max_attempts")})});setMessage("Job persistido na fila operacional.");await load()}
  async function process(id:string,fail=false){await api(`/system/jobs/${id}/process`,{method:"POST",body:JSON.stringify({simulate_failure:fail})});setMessage(fail?"Falha transitória registrada; retry agendado.":"Job processado com sucesso.");await load()}
  async function createIntegration(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);await api("/system/integrations",{method:"POST",body:JSON.stringify({provider:f.get("provider"),category:f.get("category"),environment:f.get("environment"),base_url:f.get("base_url"),credential:f.get("credential"),allowed_hosts:String(f.get("allowed_hosts")||"").split(",").map(x=>x.trim()).filter(Boolean),sla_latency_ms:Number(f.get("sla_latency_ms"))})});setMessage("Provedor configurado com allowlist e credencial protegida.");form.reset();await load()}
  async function probe(id:string,status="UP"){await api(`/system/integrations/${id}/probe`,{method:"POST",body:JSON.stringify({simulate_status:status,latency_ms:status==="UP"?35:900})});setMessage(status==="UP"?"Health check aprovado; circuito fechado.":"Falha simulada registrada no circuit breaker.");await load()}
  async function createWebhook(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);await api("/system/webhook-endpoints",{method:"POST",body:JSON.stringify({integration_id:f.get("integration_id"),name:f.get("name"),target_url:f.get("target_url"),secret:f.get("secret"),subscribed_events:[f.get("event_type")],max_attempts:5})});setMessage("Endpoint assinado criado.");form.reset();await load()}
  async function dispatch(endpoint:WebhookEndpoint,fail=false){const eventType=endpoint.subscribed_events[0]||"platform.event";await api(`/system/webhook-endpoints/${endpoint.id}/dispatch`,{method:"POST",body:JSON.stringify({event_id:`ui-webhook-${Date.now()}`,event_type:eventType,payload:{source:"dashboard",occurred_at:new Date().toISOString()},simulate_failure:fail})});setMessage(fail?"Falha simulada; entrega enviada para retentativa.":"Webhook assinado entregue no sandbox.");await load()}
  async function retry(id:string){await api(`/system/webhook-deliveries/${id}/retry`,{method:"POST",body:JSON.stringify({simulate_failure:false})});setMessage("Retentativa concluída.");await load()}
  async function incidentAction(id:string,action:string){await api(`/system/provider-incidents/${id}/action`,{method:"POST",body:JSON.stringify({action})});setMessage(action==="RESOLVE"?"Incidente resolvido.":"Incidente reconhecido pela operação.");await load()}
  async function reprocessDlq(){const ids=deliveries.filter(x=>x.status==="DEAD_LETTER").map(x=>x.id);if(!ids.length){setMessage("Não há entregas em dead letter.");return}const result=await api<{requeued:number}>("/system/webhook-deliveries/reprocess-dead-letter",{method:"POST",body:JSON.stringify({delivery_ids:ids})});setMessage(`${result.requeued} entrega(s) devolvida(s) para retentativa.`);await load()}
  async function configureOnboarding(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const id=String(f.get("integration_id"));await api(`/system/integrations/${id}/onboarding`,{method:"PUT",body:JSON.stringify({api_version:f.get("api_version"),authentication_type:f.get("authentication_type"),health_path:f.get("health_path"),reconciliation_mode:"CSV_AND_WEBHOOK",checklist:{contract_signed:false,security_approved:false}})});setMessage("Perfil técnico de onboarding configurado.");await load()}
  async function importProviderReconciliation(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const id=String(f.get("integration_id"));const body=new FormData();body.append("file",f.get("file") as File);await apiForm(`/system/integrations/${id}/reconciliation/import`,body);setMessage("Conciliação do fornecedor processada.");form.reset();await load()}
  async function generateEvidence(id:string){await api(`/system/integrations/${id}/evidence`,{method:"POST"});setMessage("Pacote de evidências de homologação gerado.");await load()}
  async function runAdapter(integration:ProviderIntegration){const spec=adapterCatalog.find(x=>x.category===integration.category);if(!spec){setMessage("Categoria sem adaptador registrado.");return}const operation=spec.capabilities[0];const payload:Record<string,string>={BAAS:{document:"12345678901"},KYC:{subject_id:"sandbox-person-001"},SIGNATURE:{signer_email:"signer@example.com"},COMMUNICATIONS:{destination:"+5511999999999",template:"welcome",channel:"WHATSAPP"},TAX:{document:"12345678000199",amount:"1500.00"}}[integration.category]||{};await api(`/system/integrations/${integration.id}/adapter/execute`,{method:"POST",body:JSON.stringify({operation,idempotency_key:`ui-adapter-${Date.now()}`,payload})});setMessage(`${spec.adapter}: ${operation} executada com sucesso.`);await load()}
  async function certify(id:string){const result=await api<AdapterCertification>(`/system/integrations/${id}/certify`,{method:"POST"});setMessage(`Certificação ${result.status}: ${result.passed_checks}/${result.total_checks} controles aprovados.`);await load()}
  async function approve(id:string,area:string){await api(`/system/integrations/${id}/go-live-approval`,{method:"PUT",body:JSON.stringify({area,decision:"APPROVED",notes:`${area} aprovado pela bancada operacional`})});setMessage(`Aprovação ${area} registrada.`);await load()}
  async function evaluateGoLive(id:string){const result=await api<GoLiveDecision>(`/system/integrations/${id}/go-live/evaluate`,{method:"POST"});setMessage(result.status==="APPROVED"?"Gate de go-live aprovado.":`Go-live bloqueado por ${result.blockers.length} critério(s).`);await load()}

  return <>
    <div className="page-heading"><div><span className="eyebrow dark">INTEGRAÇÕES HOMOLOGÁVEIS</span><h1>Operações e integrações</h1><p>Fila durável, webhooks HMAC, sandbox de provedores, retries, circuit breaker e saúde operacional.</p></div><div className="operational-icon"><Activity/></div></div>
    {message&&<div className="notice"><ShieldCheck/>{message}</div>}
    <div className="network-metrics"><Metric label="Banco" value={ready.database||"—"}/><Metric label="Jobs" value={metrics.jobs_total??0}/><Metric label="Webhooks" value={metrics.webhooks_total??0}/><Metric label="Incidentes" value={metrics.provider_incidents_open??0}/></div>

    <section className="panel"><div className="panel-title"><h2><Webhook/>Provedores e circuit breaker</h2><button onClick={()=>load()}><RefreshCw/>Atualizar</button></div>
      <form className="quick-form" onSubmit={createIntegration}><input name="provider" placeholder="Provedor" required/><select name="category"><option>BAAS</option><option>KYC</option><option>SIGNATURE</option><option>COMMUNICATIONS</option><option>TAX</option><option>CUSTOM</option></select><select name="environment"><option>SANDBOX</option><option>PRODUCTION</option></select><input name="base_url" placeholder="https://sandbox.provedor.com" required/><input name="allowed_hosts" placeholder="Hosts permitidos, separados por vírgula" required/><input name="sla_latency_ms" type="number" defaultValue="2000" min="100"/><input name="credential" type="password" placeholder="Credencial" minLength={8} required/><button>Configurar</button></form>
      <div className="table-wrap"><table className="data-table"><thead><tr><th>Provedor</th><th>Ambiente</th><th>Saúde/SLA</th><th>Circuito</th><th>Ações</th></tr></thead><tbody>{integrations.map(x=><tr key={x.id}><td><b>{x.provider}</b><small>{x.category} · credencial v{x.credential_version}</small></td><td>{x.environment}<small>{x.allowed_hosts.join(", ")}</small></td><td>{x.health_status} {x.latency_ms!==null?`· ${x.latency_ms}ms`:""}<small>Uptime observado: {x.uptime_percent}%</small></td><td><span className={`pill pill-${x.circuit_status.toLowerCase()}`}>{x.circuit_status}</span></td><td className="actions-cell"><button className="table-action" onClick={()=>probe(x.id)}><CheckCircle2/>Testar</button><button className="table-action" onClick={()=>probe(x.id,"DOWN")}>Simular falha</button></td></tr>)}</tbody></table></div>
    </section>

    <section className="panel identity-table"><div className="panel-title"><h2>Incidentes e SLA</h2></div>{incidents.map(x=><div className="session-row" key={x.id}><div><b>{x.title}</b><small>{x.severity} · {x.incident_type} · {x.details}</small></div><div className="actions-cell"><span className={`pill pill-${x.status.toLowerCase()}`}>{x.status}</span>{x.status==="OPEN"&&<button className="table-action" onClick={()=>incidentAction(x.id,"ACKNOWLEDGE")}>Reconhecer</button>}{x.status!=="RESOLVED"&&<button className="table-action" onClick={()=>incidentAction(x.id,"RESOLVE")}>Resolver</button>}</div></div>)}</section>

    <section className="panel"><div className="panel-title"><h2>Adaptadores de fornecedores</h2></div><div className="module-checklist">{adapterCatalog.map(x=><span key={x.category}><CheckCircle2/>{x.category}: {x.adapter} · {x.capabilities.join(", ")}</span>)}</div><div className="table-wrap"><table className="data-table"><thead><tr><th>Integração</th><th>Adaptador</th><th>Ambiente</th><th>Ação</th></tr></thead><tbody>{integrations.filter(x=>adapterCatalog.some(a=>a.category===x.category)).map(x=><tr key={x.id}><td><b>{x.provider}</b><small>{x.category}</small></td><td>{adapterCatalog.find(a=>a.category===x.category)?.version}</td><td>{x.environment}</td><td><button className="table-action" disabled={x.environment!=="SANDBOX"} onClick={()=>runAdapter(x)}><Play/>Executar teste</button></td></tr>)}</tbody></table></div>{adapterExecutions.slice(0,10).map(x=><div className="session-row" key={x.id}><div><b>{x.category} · {x.operation}</b><small>{x.adapter_name} {x.adapter_version} · {x.external_id}</small></div><span className={`pill pill-${x.status.toLowerCase()}`}>{x.status}</span></div>)}</section>

    <section className="panel"><div className="panel-title"><h2>Certificação e gate de go-live</h2></div>{integrations.filter(x=>adapterCatalog.some(a=>a.category===x.category)).map(x=>{const certification=certifications.find(c=>c.integration_id===x.id);const decision=goLiveDecisions.find(d=>d.integration_id===x.id);const approved=new Set(goLiveApprovals.filter(a=>a.integration_id===x.id&&a.decision==="APPROVED").map(a=>a.area));return <div className="session-row" key={x.id}><div><b>{x.provider} · {x.environment}</b><small>Certificação: {certification?`${certification.status} ${certification.passed_checks}/${certification.total_checks}`:"não executada"} · Aprovações: {approved.size}/4{decision?` · Gate ${decision.status}`:""}</small>{decision?.blockers.length?<small>Bloqueios: {decision.blockers.join(", ")}</small>:null}</div><div className="actions-cell"><button className="table-action" onClick={()=>certify(x.id)}>Certificar</button>{["SECURITY","LEGAL","COMPLIANCE","OPERATIONS"].filter(a=>!approved.has(a)).map(a=><button className="table-action" key={a} onClick={()=>approve(x.id,a)}>{a}</button>)}<button className="table-action" onClick={()=>evaluateGoLive(x.id)}>Avaliar go-live</button></div></div>})}</section>

    <section className="panel"><div className="panel-title"><h2>Onboarding e homologação</h2></div><form className="quick-form" onSubmit={configureOnboarding}><select name="integration_id" required><option value="">Fornecedor</option>{integrations.map(x=><option key={x.id} value={x.id}>{x.provider}</option>)}</select><input name="api_version" defaultValue="v1" placeholder="Versão da API"/><select name="authentication_type"><option>BEARER</option><option>API_KEY</option><option>MTLS</option><option>OAUTH2</option></select><input name="health_path" defaultValue="/health"/><button>Configurar perfil</button></form>{profiles.map(x=><div className="session-row" key={x.id}><div><b>{integrations.find(i=>i.id===x.integration_id)?.provider||x.integration_id}</b><small>{x.api_version} · {x.authentication_type} · {x.reconciliation_mode}</small></div><div className="actions-cell"><span className={`pill pill-${x.status.toLowerCase()}`}>{x.status}</span><button className="table-action" onClick={()=>generateEvidence(x.integration_id)}>Gerar evidências</button></div></div>)}</section>

    <section className="panel"><div className="panel-title"><h2>Conciliação BaaS/escrow</h2></div><form className="quick-form" onSubmit={importProviderReconciliation}><select name="integration_id" required><option value="">Fornecedor</option>{integrations.filter(x=>x.category==="BAAS").map(x=><option key={x.id} value={x.id}>{x.provider}</option>)}</select><input name="file" type="file" accept=".csv,text/csv" required/><button>Importar CSV</button></form>{reconciliations.map(x=><div className="session-row" key={x.id}><div><b>{x.source_reference}</b><small>{x.matched_items} conciliados · {x.divergent_items} divergentes · hash {x.content_hash.slice(0,12)}</small></div><span className={`pill pill-${x.status.toLowerCase()}`}>{x.status}</span></div>)}</section>

    <section className="panel"><h2>Evidências recentes</h2><div className="module-checklist">{evidences.slice(0,12).map(x=><span key={x.id}><CheckCircle2/>{x.control_key}: {x.result} · {x.evidence_hash.slice(0,10)}</span>)}</div></section>

    <section className="panel"><h2><Webhook/>Webhooks assinados</h2>
      <form className="quick-form" onSubmit={createWebhook}><select name="integration_id" required><option value="">Provedor</option>{integrations.map(x=><option key={x.id} value={x.id}>{x.provider} · {x.environment}</option>)}</select><input name="name" placeholder="Nome do endpoint" required/><input name="target_url" placeholder="mock://erp/webhooks" required/><input name="event_type" placeholder="payment.confirmed" required/><input name="secret" type="password" placeholder="Secret HMAC (mín. 16)" minLength={16} required/><button>Criar endpoint</button></form>
      {endpoints.map(x=><div className="session-row" key={x.id}><div><b>{x.name}</b><small>{x.target_url} · {x.subscribed_events.join(", ")}</small></div><div className="actions-cell"><button className="table-action" onClick={()=>dispatch(x)}><Play/>Enviar teste</button><button className="table-action" onClick={()=>dispatch(x,true)}>Testar retry</button></div></div>)}
    </section>

    <section className="panel identity-table"><div className="panel-title"><h2>Entregas recentes</h2><button onClick={reprocessDlq}><RefreshCw/>Reprocessar dead letter</button></div>{deliveries.map(x=><div className="session-row" key={x.id}><div><b>{x.event_type}</b><small>{x.event_id} · tentativa {x.attempts}/{x.max_attempts}{x.last_error?` · ${x.last_error}`:""}</small></div><div className="actions-cell"><span className={`pill pill-${x.status.toLowerCase()}`}>{x.status}</span>{x.status==="RETRY_SCHEDULED"&&<button className="table-action" onClick={()=>retry(x.id)}><RefreshCw/>Retentar</button>}</div></div>)}</section>

    <section className="panel"><form className="quick-form" onSubmit={createJob}><select name="job_type"><option>RECONCILIATION_REFRESH</option><option>COLLECTION_REFRESH</option><option>COMMUNICATION_DELIVERY</option><option>EXECUTIVE_REPORT</option><option>PROVIDER_HEALTH_MONITOR</option><option>DEAD_LETTER_REPROCESS</option></select><input name="max_attempts" type="number" min="1" max="10" defaultValue="3"/><button>Criar job</button></form></section>
    <section className="panel identity-table"><div className="panel-title"><h2>Fila operacional</h2></div>{jobs.map(x=><div className="session-row" key={x.id}><div><b>{x.job_type}</b><small>{x.status} · tentativa {x.attempts}/{x.max_attempts}{x.last_error?` · ${x.last_error}`:""}</small></div><div className="actions-cell"><span className={`pill pill-${x.status.toLowerCase()}`}>{x.status}</span>{!["COMPLETED","DEAD_LETTER"].includes(x.status)&&<><button className="table-action" onClick={()=>process(x.id)}><Play/>Processar</button><button className="table-action" onClick={()=>process(x.id,true)}>Simular falha</button></>}</div></div>)}</section>
    <section className="panel"><h2><Database/>Checklist de homologação</h2><div className="module-checklist">{[...(homologation?.blocking_issues||[]),...Object.entries(homologation?.external_providers||{}).map(([k,v])=>`${k}: ${v}`)].map(x=><span key={x}><CheckCircle2/>{x}</span>)}</div></section>
  </>;
}
