"use client";
import { Building2, CheckCircle2, Download, ShieldCheck } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { api, downloadApi, StructuredProperty, StructuredPropertyEvent } from "@/lib/api";

const brl=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
export function StructuredPropertiesModule(){
 const [cases,setCases]=useState<StructuredProperty[]>([]),[events,setEvents]=useState<StructuredPropertyEvent[]>([]),[message,setMessage]=useState("");
 const load=()=>Promise.all([api<StructuredProperty[]>("/structured-properties"),api<StructuredPropertyEvent[]>("/structured-properties/events")]).then(([c,e])=>{setCases(c);setEvents(e)});
 useEffect(()=>{void load()},[]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);try{await api("/structured-properties",{method:"POST",body:JSON.stringify({buyer_document:f.get("buyer_document"),seller_document:f.get("seller_document"),has_lien_debt:f.get("has_lien_debt")==="on",unregistered_construction:f.get("unregistered_construction")==="on",land_appraisal_value:f.get("land_appraisal_value"),future_appraisal_value:f.get("future_appraisal_value"),estimated_debt:f.get("estimated_debt")||"0"})});setMessage("Esteira criada com LTV de 40%, memória de cálculo e legal hold.");form.reset();await load()}catch(x){setMessage(x instanceof Error?x.message:"Falha ao criar esteira")}}
 async function phase1(id:string){try{await api(`/structured-properties/${id}/phase-1-release`,{method:"POST",body:"{}"});setMessage("Fase 1 preparada somente em sandbox; cronômetro de 90 dias iniciado.");await load()}catch(x){setMessage(x instanceof Error?x.message:"Gate pendente")}}
 return <><div className="page-heading"><div><span className="eyebrow dark">NINA REAL ASSETS</span><h1>Imóveis estruturados</h1><p>Garantia limpa, interveniente quitante, construção não averbada e payout em duas fases.</p></div><div className="operational-icon"><Building2/></div></div>{message&&<div className="notice"><ShieldCheck/>{message}</div>}<section className="panel"><form className="quick-form" onSubmit={create}><input name="buyer_document" placeholder="CPF/CNPJ comprador" required/><input name="seller_document" placeholder="CPF/CNPJ vendedor" required/><input name="land_appraisal_value" type="number" placeholder="AVM do lote" required/><input name="future_appraisal_value" type="number" placeholder="AVM futuro" required/><input name="estimated_debt" type="number" placeholder="Dívida estimada"/><label><input name="has_lien_debt" type="checkbox"/> Interveniente quitante</label><label><input name="unregistered_construction" type="checkbox"/> Construção não averbada</label><button>Criar esteira</button></form></section><section className="panel"><div className="table-wrap"><table className="data-table"><thead><tr><th>Caso</th><th>Rota</th><th>LTV / fases</th><th>IQ</th><th>Status</th><th>Ações</th></tr></thead><tbody>{cases.map(x=><tr key={x.id}><td><b>{x.case_reference}</b><small>hash {x.evidence_hash.slice(0,12)}</small></td><td>{x.route}</td><td><b>{brl.format(Number(x.gross_payout))}</b><small>F1 {brl.format(Number(x.phase1_amount))} · F2 {brl.format(Number(x.phase2_amount))}</small></td><td>{x.iq_status}</td><td><span className={`pill pill-${x.phase_status.toLowerCase()}`}>{x.phase_status}</span><small>legal hold {x.legal_hold?"ATIVO":"LIBERADO"}</small></td><td><div className="actions-cell"><button className="table-action" onClick={()=>phase1(x.id)} disabled={!['AWAITING_REGISTRY','AWAITING_PHASE1_APPROVAL'].includes(x.phase_status)}><CheckCircle2/>Fase 1 sandbox</button><button className="table-action" onClick={()=>downloadApi(`/structured-properties/${x.id}/registry-requirement.pdf`,`${x.case_reference}-requerimento.pdf`)}><Download/>Requerimento</button></div></td></tr>)}</tbody></table></div></section><section className="panel"><h2>Trilha imutável</h2><div className="module-checklist">{events.slice(0,12).map(x=><span key={x.id}><CheckCircle2/>{x.event_type} · {x.status} · {x.evidence_hash.slice(0,10)}</span>)}</div><small className="form-help">Nenhum Pix, registro, perda de direito ou liberação de Fase 2 ocorre automaticamente.</small></section></>
}
