"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, FileCheck2, MailCheck, MessageSquareText, Receipt, Send, ShieldCheck } from "lucide-react";
import { api, CommunicationConsent, CommunicationDelivery, CommunicationTemplate, Lead, TaxClosing, TaxDocument, TaxException, User } from "@/lib/api";

const brl=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});

export function TaxTechModule(){
  const [users,setUsers]=useState<User[]>([]),[documents,setDocuments]=useState<TaxDocument[]>([]),[closings,setClosings]=useState<TaxClosing[]>([]),[exceptions,setExceptions]=useState<TaxException[]>([]),[message,setMessage]=useState("");
  const load=useCallback(()=>Promise.all([api<User[]>("/admin/users"),api<TaxDocument[]>("/tax/documents"),api<TaxClosing[]>("/tax/closings"),api<TaxException[]>("/tax/exceptions")]).then(([u,d,c,e])=>{setUsers(u);setDocuments(d);setClosings(c);setExceptions(e)}),[]);useEffect(()=>{load().catch(e=>setMessage(e.message))},[load]);
  async function issue(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await api("/tax/documents",{method:"POST",body:JSON.stringify({user_id:f.get("user_id"),reference_month:f.get("reference_month"),gross_amount:f.get("gross_amount"),tax_amount:f.get("tax_amount"),content:f.get("content")})});setMessage("NFS-e mock validada e vinculada ao parceiro.");await load()}
  async function close(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const result=await api<TaxClosing>("/tax/closings",{method:"POST",body:JSON.stringify({reference_month:f.get("reference_month")})});setMessage(`Fechamento ${result.status}: ${result.exception_count} exceções.`);await load()}
  const eligible=useMemo(()=>closings.reduce((s,x)=>s+Number(x.eligible_payout),0),[closings]);
  return <><Heading title="TaxTech e fechamento fiscal" text="NFS-e simulada, elegibilidade de payout, fechamento mensal e fila de exceções." icon={<Receipt/>}/>{message&&<Notice text={message}/>}<Metrics items={[["Documentos",documents.length],["Fechamentos",closings.length],["Exceções abertas",exceptions.filter(x=>x.status==="OPEN").length],["Payout elegível",brl.format(eligible)]]}/><div className="tax-comms-grid"><section className="panel"><h2><FileCheck2/>Registrar NFS-e mock</h2><form className="stack-form" onSubmit={issue}><select name="user_id">{users.map(u=><option value={u.id} key={u.id}>{u.name}</option>)}</select><input name="reference_month" type="month" required/><input name="gross_amount" type="number" placeholder="Valor bruto" required/><input name="tax_amount" type="number" placeholder="Imposto" defaultValue="0" required/><textarea name="content" defaultValue="<NFS-e>evidência fiscal simulada</NFS-e>" required/><button>Validar documento</button></form></section><section className="panel"><h2><CheckCircle2/>Fechar competência</h2><form className="stack-form" onSubmit={close}><input name="reference_month" type="month" required/><button>Conciliar comissões e documentos</button></form>{closings.map(x=><div className="compact-row" key={x.id}><span><b>{x.reference_month}</b><small>{x.exception_count} exceções · elegível {brl.format(Number(x.eligible_payout))}</small></span><span className={`pill pill-${x.status.toLowerCase()}`}>{x.status}</span></div>)}</section></div><section className="panel identity-table"><h2>Fila de exceções fiscais</h2>{exceptions.map(x=><div className="session-row" key={x.id}><div><b>{x.reason}</b><small>{users.find(u=>u.id===x.user_id)?.name} · {brl.format(Number(x.amount))}</small></div><span className={`pill pill-${x.status.toLowerCase()}`}>{x.status}</span></div>)}</section></>
}

export function CommunicationsModule(){
  const [templates,setTemplates]=useState<CommunicationTemplate[]>([]),[consents,setConsents]=useState<CommunicationConsent[]>([]),[deliveries,setDeliveries]=useState<CommunicationDelivery[]>([]),[leads,setLeads]=useState<Lead[]>([]),[message,setMessage]=useState("");
  const load=useCallback(()=>Promise.all([api<CommunicationTemplate[]>("/communications/templates"),api<CommunicationConsent[]>("/communications/consents"),api<CommunicationDelivery[]>("/communications/deliveries"),api<Lead[]>("/leads")]).then(([t,c,d,l])=>{setTemplates(t);setConsents(c);setDeliveries(d);setLeads(l)}),[]);useEffect(()=>{load().catch(e=>setMessage(e.message))},[load]);
  async function template(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await api("/communications/templates",{method:"POST",body:JSON.stringify({key:f.get("key"),channel:f.get("channel"),subject:f.get("subject")||null,body:f.get("body"),purpose:f.get("purpose")})});setMessage("Nova versão do template publicada.");await load()}
  async function consent(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await api("/communications/consents",{method:"POST",body:JSON.stringify({subject_type:"LEAD",subject_id:f.get("subject_id"),channel:f.get("channel"),status:f.get("status"),source:"BACKOFFICE",evidence:{recorded_by:"dashboard"}})});setMessage("Preferência de comunicação atualizada.");await load()}
  async function send(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),lead=leads.find(x=>x.id===f.get("subject_id"));await api("/communications/send",{method:"POST",body:JSON.stringify({template_id:f.get("template_id"),subject_type:"LEAD",subject_id:f.get("subject_id"),destination:lead?.phone,idempotency_key:`ui-message-${Date.now()}`,variables:{name:lead?.name}})});setMessage("Mensagem enfileirada no adaptador mock.");await load()}
  async function deliver(id:string){await api(`/communications/deliveries/${id}/mock-deliver`,{method:"POST"});setMessage("Entrega confirmada pelo provedor simulado.");await load()}
  return <><Heading title="Central de comunicações" text="Templates versionados, consentimentos, opt-out e rastreamento multicanal." icon={<MessageSquareText/>}/>{message&&<Notice text={message}/>}<Metrics items={[["Templates",templates.length],["Opt-ins",consents.filter(x=>x.status==="OPT_IN").length],["Opt-outs",consents.filter(x=>x.status==="OPT_OUT").length],["Entregues",deliveries.filter(x=>x.status==="DELIVERED").length]]}/><div className="tax-comms-grid"><section className="panel"><h2><MailCheck/>Template versionado</h2><form className="stack-form" onSubmit={template}><input name="key" placeholder="Chave do template" required/><select name="channel"><option>WHATSAPP</option><option>EMAIL</option><option>IN_APP</option></select><select name="purpose"><option>TRANSACTIONAL</option><option>MARKETING</option></select><input name="subject" placeholder="Assunto (e-mail)"/><textarea name="body" defaultValue="Olá {{name}}, temos uma atualização para você." required/><button>Publicar nova versão</button></form></section><section className="panel"><h2><ShieldCheck/>Consentimento e opt-out</h2><form className="stack-form" onSubmit={consent}><select name="subject_id">{leads.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><select name="channel"><option>WHATSAPP</option><option>EMAIL</option><option>IN_APP</option></select><select name="status"><option>OPT_IN</option><option>OPT_OUT</option></select><button>Registrar preferência</button></form></section></div><section className="panel comm-send"><h2><Send/>Simular envio</h2><form className="quick-form" onSubmit={send}><select name="template_id">{templates.filter(x=>x.active).map(x=><option value={x.id} key={x.id}>{x.key} v{x.version} · {x.channel}</option>)}</select><select name="subject_id">{leads.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><button>Enfileirar mensagem</button></form></section><section className="panel identity-table"><h2>Histórico de entregas</h2>{deliveries.map(x=><div className="session-row" key={x.id}><div><b>{templates.find(t=>t.id===x.template_id)?.key}</b><small>{x.destination_masked} · {x.rendered_body}</small></div><div className="actions-cell"><span className={`pill pill-${x.status.toLowerCase()}`}>{x.status}</span>{x.status==="QUEUED"&&<button className="table-action" onClick={()=>deliver(x.id)}>Entregar mock</button>}</div></div>)}</section></>
}

function Heading({title,text,icon}:{title:string;text:string;icon:React.ReactNode}){return <div className="page-heading"><div><span className="eyebrow dark">OPERAÇÃO LETTER</span><h1>{title}</h1><p>{text}</p></div><div className="operational-icon">{icon}</div></div>}
function Notice({text}:{text:string}){return <div className="notice"><ShieldCheck/>{text}</div>}
function Metrics({items}:{items:[string,string|number][]}){return <div className="network-metrics">{items.map(([label,value])=><article key={label}><small>{label}</small><strong>{value}</strong></article>)}</div>}
