"""taxtech and communications

Revision ID: 09c4acc8ee4e
Revises: a2c0a1af2b4e
Create Date: 2026-08-03 15:28:28.613849
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '09c4acc8ee4e'
down_revision: Union[str, Sequence[str], None] = 'a2c0a1af2b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_consents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('subject_type', sa.String(length=30), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'subject_type', 'subject_id', 'channel')
    )
    op.create_index(op.f('ix_communication_consents_channel'), 'communication_consents', ['channel'], unique=False)
    op.create_index(op.f('ix_communication_consents_organization_id'), 'communication_consents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_communication_consents_status'), 'communication_consents', ['status'], unique=False)
    op.create_index(op.f('ix_communication_consents_subject_id'), 'communication_consents', ['subject_id'], unique=False)
    op.create_table('communication_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=180), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'key', 'channel', 'version')
    )
    op.create_index(op.f('ix_communication_templates_channel'), 'communication_templates', ['channel'], unique=False)
    op.create_index(op.f('ix_communication_templates_key'), 'communication_templates', ['key'], unique=False)
    op.create_index(op.f('ix_communication_templates_organization_id'), 'communication_templates', ['organization_id'], unique=False)
    op.create_table('communication_deliveries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('subject_type', sa.String(length=30), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('destination_masked', sa.String(length=180), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('rendered_body', sa.Text(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=120), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['communication_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_deliveries_idempotency_key'), 'communication_deliveries', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_communication_deliveries_organization_id'), 'communication_deliveries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_communication_deliveries_status'), 'communication_deliveries', ['status'], unique=False)
    op.create_index(op.f('ix_communication_deliveries_subject_id'), 'communication_deliveries', ['subject_id'], unique=False)
    op.create_index(op.f('ix_communication_deliveries_template_id'), 'communication_deliveries', ['template_id'], unique=False)
    op.create_table('tax_closings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('reference_month', sa.String(length=7), nullable=False),
    sa.Column('gross_commissions', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('documented_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('eligible_payout', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('exception_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('closed_by_id', sa.String(length=36), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'reference_month')
    )
    op.create_index(op.f('ix_tax_closings_organization_id'), 'tax_closings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tax_closings_reference_month'), 'tax_closings', ['reference_month'], unique=False)
    op.create_index(op.f('ix_tax_closings_status'), 'tax_closings', ['status'], unique=False)
    op.create_table('tax_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('reference_month', sa.String(length=7), nullable=False),
    sa.Column('document_number', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index(op.f('ix_tax_documents_document_number'), 'tax_documents', ['document_number'], unique=True)
    op.create_index(op.f('ix_tax_documents_organization_id'), 'tax_documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tax_documents_reference_month'), 'tax_documents', ['reference_month'], unique=False)
    op.create_index(op.f('ix_tax_documents_status'), 'tax_documents', ['status'], unique=False)
    op.create_index(op.f('ix_tax_documents_user_id'), 'tax_documents', ['user_id'], unique=False)
    op.create_table('tax_exceptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('closing_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resolved_by_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['closing_id'], ['tax_closings.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_exceptions_closing_id'), 'tax_exceptions', ['closing_id'], unique=False)
    op.create_index(op.f('ix_tax_exceptions_organization_id'), 'tax_exceptions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tax_exceptions_status'), 'tax_exceptions', ['status'], unique=False)
    op.create_index(op.f('ix_tax_exceptions_user_id'), 'tax_exceptions', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_exceptions_user_id'), table_name='tax_exceptions')
    op.drop_index(op.f('ix_tax_exceptions_status'), table_name='tax_exceptions')
    op.drop_index(op.f('ix_tax_exceptions_organization_id'), table_name='tax_exceptions')
    op.drop_index(op.f('ix_tax_exceptions_closing_id'), table_name='tax_exceptions')
    op.drop_table('tax_exceptions')
    op.drop_index(op.f('ix_tax_documents_user_id'), table_name='tax_documents')
    op.drop_index(op.f('ix_tax_documents_status'), table_name='tax_documents')
    op.drop_index(op.f('ix_tax_documents_reference_month'), table_name='tax_documents')
    op.drop_index(op.f('ix_tax_documents_organization_id'), table_name='tax_documents')
    op.drop_index(op.f('ix_tax_documents_document_number'), table_name='tax_documents')
    op.drop_table('tax_documents')
    op.drop_index(op.f('ix_tax_closings_status'), table_name='tax_closings')
    op.drop_index(op.f('ix_tax_closings_reference_month'), table_name='tax_closings')
    op.drop_index(op.f('ix_tax_closings_organization_id'), table_name='tax_closings')
    op.drop_table('tax_closings')
    op.drop_index(op.f('ix_communication_deliveries_template_id'), table_name='communication_deliveries')
    op.drop_index(op.f('ix_communication_deliveries_subject_id'), table_name='communication_deliveries')
    op.drop_index(op.f('ix_communication_deliveries_status'), table_name='communication_deliveries')
    op.drop_index(op.f('ix_communication_deliveries_organization_id'), table_name='communication_deliveries')
    op.drop_index(op.f('ix_communication_deliveries_idempotency_key'), table_name='communication_deliveries')
    op.drop_table('communication_deliveries')
    op.drop_index(op.f('ix_communication_templates_organization_id'), table_name='communication_templates')
    op.drop_index(op.f('ix_communication_templates_key'), table_name='communication_templates')
    op.drop_index(op.f('ix_communication_templates_channel'), table_name='communication_templates')
    op.drop_table('communication_templates')
    op.drop_index(op.f('ix_communication_consents_subject_id'), table_name='communication_consents')
    op.drop_index(op.f('ix_communication_consents_status'), table_name='communication_consents')
    op.drop_index(op.f('ix_communication_consents_organization_id'), table_name='communication_consents')
    op.drop_index(op.f('ix_communication_consents_channel'), table_name='communication_consents')
    op.drop_table('communication_consents')
    # ### end Alembic commands ###
