"""real connectors incidents sla and dead letter operations

Revision ID: 0bf0b9a1af98
Revises: 99dae05d6519
Create Date: 2026-08-03 16:26:43.630919
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0bf0b9a1af98'
down_revision: Union[str, Sequence[str], None] = '99dae05d6519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_request_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('integration_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['provider_integrations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_request_logs_created_at'), 'provider_request_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_provider_request_logs_integration_id'), 'provider_request_logs', ['integration_id'], unique=False)
    op.create_index(op.f('ix_provider_request_logs_organization_id'), 'provider_request_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_provider_request_logs_success'), 'provider_request_logs', ['success'], unique=False)
    op.create_table('provider_incidents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('integration_id', sa.String(length=36), nullable=False),
    sa.Column('incident_type', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('details', sa.String(length=1000), nullable=False),
    sa.Column('acknowledged_by_id', sa.String(length=36), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['integration_id'], ['provider_integrations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_incidents_incident_type'), 'provider_incidents', ['incident_type'], unique=False)
    op.create_index(op.f('ix_provider_incidents_integration_id'), 'provider_incidents', ['integration_id'], unique=False)
    op.create_index(op.f('ix_provider_incidents_organization_id'), 'provider_incidents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_provider_incidents_severity'), 'provider_incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_provider_incidents_status'), 'provider_incidents', ['status'], unique=False)
    op.add_column('provider_integrations', sa.Column('allowed_hosts_json', sa.Text(), nullable=False, server_default='[]'))
    op.add_column('provider_integrations', sa.Column('credential_version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('provider_integrations', sa.Column('credential_rotated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('provider_integrations', sa.Column('sla_latency_ms', sa.Integer(), nullable=False, server_default='2000'))
    op.add_column('provider_integrations', sa.Column('total_checks', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('provider_integrations', sa.Column('successful_checks', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_integrations', 'successful_checks')
    op.drop_column('provider_integrations', 'total_checks')
    op.drop_column('provider_integrations', 'sla_latency_ms')
    op.drop_column('provider_integrations', 'credential_rotated_at')
    op.drop_column('provider_integrations', 'credential_version')
    op.drop_column('provider_integrations', 'allowed_hosts_json')
    op.drop_index(op.f('ix_provider_incidents_status'), table_name='provider_incidents')
    op.drop_index(op.f('ix_provider_incidents_severity'), table_name='provider_incidents')
    op.drop_index(op.f('ix_provider_incidents_organization_id'), table_name='provider_incidents')
    op.drop_index(op.f('ix_provider_incidents_integration_id'), table_name='provider_incidents')
    op.drop_index(op.f('ix_provider_incidents_incident_type'), table_name='provider_incidents')
    op.drop_table('provider_incidents')
    op.drop_index(op.f('ix_provider_request_logs_success'), table_name='provider_request_logs')
    op.drop_index(op.f('ix_provider_request_logs_organization_id'), table_name='provider_request_logs')
    op.drop_index(op.f('ix_provider_request_logs_integration_id'), table_name='provider_request_logs')
    op.drop_index(op.f('ix_provider_request_logs_created_at'), table_name='provider_request_logs')
    op.drop_table('provider_request_logs')
    # ### end Alembic commands ###
