"""nina asset distress lifecycle and legal gates

Revision ID: 38afc1fa2212
Revises: 4091045f974c
Create Date: 2026-08-10 14:48:39.204101
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '38afc1fa2212'
down_revision: Union[str, Sequence[str], None] = '4091045f974c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nina_distress_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('delinquency_case_id', sa.String(length=36), nullable=False),
    sa.Column('operation_id', sa.String(length=36), nullable=True),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('days_overdue', sa.Integer(), nullable=False),
    sa.Column('fiscal_check_status', sa.String(length=30), nullable=False),
    sa.Column('cash_hold_status', sa.String(length=30), nullable=False),
    sa.Column('legal_notice_status', sa.String(length=30), nullable=False),
    sa.Column('caducity_status', sa.String(length=30), nullable=False),
    sa.Column('auction_status', sa.String(length=30), nullable=False),
    sa.Column('appraisal_value_avm', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('opening_price_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('floor_price_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('daily_reduction_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('current_auction_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('voluntary_vacate_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('photo_storage_reference', sa.String(length=500), nullable=True),
    sa.Column('matched_quota_id', sa.String(length=36), nullable=True),
    sa.Column('legal_hold', sa.Boolean(), nullable=False),
    sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['delinquency_case_id'], ['delinquency_cases.id'], ),
    sa.ForeignKeyConstraint(['matched_quota_id'], ['quotas.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nina_distress_cases_auction_status'), 'nina_distress_cases', ['auction_status'], unique=False)
    op.create_index(op.f('ix_nina_distress_cases_caducity_status'), 'nina_distress_cases', ['caducity_status'], unique=False)
    op.create_index(op.f('ix_nina_distress_cases_cash_hold_status'), 'nina_distress_cases', ['cash_hold_status'], unique=False)
    op.create_index(op.f('ix_nina_distress_cases_days_overdue'), 'nina_distress_cases', ['days_overdue'], unique=False)
    op.create_index(op.f('ix_nina_distress_cases_delinquency_case_id'), 'nina_distress_cases', ['delinquency_case_id'], unique=True)
    op.create_index(op.f('ix_nina_distress_cases_fiscal_check_status'), 'nina_distress_cases', ['fiscal_check_status'], unique=False)
    op.create_index(op.f('ix_nina_distress_cases_legal_hold'), 'nina_distress_cases', ['legal_hold'], unique=False)
    op.create_index(op.f('ix_nina_distress_cases_legal_notice_status'), 'nina_distress_cases', ['legal_notice_status'], unique=False)
    op.create_index(op.f('ix_nina_distress_cases_matched_quota_id'), 'nina_distress_cases', ['matched_quota_id'], unique=False)
    op.create_index(op.f('ix_nina_distress_cases_next_action_at'), 'nina_distress_cases', ['next_action_at'], unique=False)
    op.create_index(op.f('ix_nina_distress_cases_operation_id'), 'nina_distress_cases', ['operation_id'], unique=False)
    op.create_index(op.f('ix_nina_distress_cases_organization_id'), 'nina_distress_cases', ['organization_id'], unique=False)
    op.create_index(op.f('ix_nina_distress_cases_stage'), 'nina_distress_cases', ['stage'], unique=False)
    op.create_table('nina_critical_approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('gate', sa.String(length=40), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=False),
    sa.Column('approver_id', sa.String(length=36), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['nina_distress_cases.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'gate', 'approver_id')
    )
    op.create_index(op.f('ix_nina_critical_approvals_approver_id'), 'nina_critical_approvals', ['approver_id'], unique=False)
    op.create_index(op.f('ix_nina_critical_approvals_case_id'), 'nina_critical_approvals', ['case_id'], unique=False)
    op.create_index(op.f('ix_nina_critical_approvals_decided_at'), 'nina_critical_approvals', ['decided_at'], unique=False)
    op.create_index(op.f('ix_nina_critical_approvals_decision'), 'nina_critical_approvals', ['decision'], unique=False)
    op.create_index(op.f('ix_nina_critical_approvals_gate'), 'nina_critical_approvals', ['gate'], unique=False)
    op.create_index(op.f('ix_nina_critical_approvals_organization_id'), 'nina_critical_approvals', ['organization_id'], unique=False)
    op.create_table('nina_distress_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('event_key', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('evidence_hash', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['nina_distress_cases.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'event_key')
    )
    op.create_index(op.f('ix_nina_distress_events_case_id'), 'nina_distress_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_nina_distress_events_event_key'), 'nina_distress_events', ['event_key'], unique=False)
    op.create_index(op.f('ix_nina_distress_events_event_type'), 'nina_distress_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_nina_distress_events_evidence_hash'), 'nina_distress_events', ['evidence_hash'], unique=True)
    op.create_index(op.f('ix_nina_distress_events_occurred_at'), 'nina_distress_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_nina_distress_events_organization_id'), 'nina_distress_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_nina_distress_events_status'), 'nina_distress_events', ['status'], unique=False)
    op.create_table('nina_legal_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['nina_distress_cases.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'document_type', 'version')
    )
    op.create_index(op.f('ix_nina_legal_documents_case_id'), 'nina_legal_documents', ['case_id'], unique=False)
    op.create_index(op.f('ix_nina_legal_documents_content_hash'), 'nina_legal_documents', ['content_hash'], unique=True)
    op.create_index(op.f('ix_nina_legal_documents_document_type'), 'nina_legal_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_nina_legal_documents_organization_id'), 'nina_legal_documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_nina_legal_documents_status'), 'nina_legal_documents', ['status'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nina_legal_documents_status'), table_name='nina_legal_documents')
    op.drop_index(op.f('ix_nina_legal_documents_organization_id'), table_name='nina_legal_documents')
    op.drop_index(op.f('ix_nina_legal_documents_document_type'), table_name='nina_legal_documents')
    op.drop_index(op.f('ix_nina_legal_documents_content_hash'), table_name='nina_legal_documents')
    op.drop_index(op.f('ix_nina_legal_documents_case_id'), table_name='nina_legal_documents')
    op.drop_table('nina_legal_documents')
    op.drop_index(op.f('ix_nina_distress_events_status'), table_name='nina_distress_events')
    op.drop_index(op.f('ix_nina_distress_events_organization_id'), table_name='nina_distress_events')
    op.drop_index(op.f('ix_nina_distress_events_occurred_at'), table_name='nina_distress_events')
    op.drop_index(op.f('ix_nina_distress_events_evidence_hash'), table_name='nina_distress_events')
    op.drop_index(op.f('ix_nina_distress_events_event_type'), table_name='nina_distress_events')
    op.drop_index(op.f('ix_nina_distress_events_event_key'), table_name='nina_distress_events')
    op.drop_index(op.f('ix_nina_distress_events_case_id'), table_name='nina_distress_events')
    op.drop_table('nina_distress_events')
    op.drop_index(op.f('ix_nina_critical_approvals_organization_id'), table_name='nina_critical_approvals')
    op.drop_index(op.f('ix_nina_critical_approvals_gate'), table_name='nina_critical_approvals')
    op.drop_index(op.f('ix_nina_critical_approvals_decision'), table_name='nina_critical_approvals')
    op.drop_index(op.f('ix_nina_critical_approvals_decided_at'), table_name='nina_critical_approvals')
    op.drop_index(op.f('ix_nina_critical_approvals_case_id'), table_name='nina_critical_approvals')
    op.drop_index(op.f('ix_nina_critical_approvals_approver_id'), table_name='nina_critical_approvals')
    op.drop_table('nina_critical_approvals')
    op.drop_index(op.f('ix_nina_distress_cases_stage'), table_name='nina_distress_cases')
    op.drop_index(op.f('ix_nina_distress_cases_organization_id'), table_name='nina_distress_cases')
    op.drop_index(op.f('ix_nina_distress_cases_operation_id'), table_name='nina_distress_cases')
    op.drop_index(op.f('ix_nina_distress_cases_next_action_at'), table_name='nina_distress_cases')
    op.drop_index(op.f('ix_nina_distress_cases_matched_quota_id'), table_name='nina_distress_cases')
    op.drop_index(op.f('ix_nina_distress_cases_legal_notice_status'), table_name='nina_distress_cases')
    op.drop_index(op.f('ix_nina_distress_cases_legal_hold'), table_name='nina_distress_cases')
    op.drop_index(op.f('ix_nina_distress_cases_fiscal_check_status'), table_name='nina_distress_cases')
    op.drop_index(op.f('ix_nina_distress_cases_delinquency_case_id'), table_name='nina_distress_cases')
    op.drop_index(op.f('ix_nina_distress_cases_days_overdue'), table_name='nina_distress_cases')
    op.drop_index(op.f('ix_nina_distress_cases_cash_hold_status'), table_name='nina_distress_cases')
    op.drop_index(op.f('ix_nina_distress_cases_caducity_status'), table_name='nina_distress_cases')
    op.drop_index(op.f('ix_nina_distress_cases_auction_status'), table_name='nina_distress_cases')
    op.drop_table('nina_distress_cases')
    # ### end Alembic commands ###
