"""adapter certification approvals and go live gates

Revision ID: 4091045f974c
Revises: fecc050b709e
Create Date: 2026-08-03 17:06:44.686310
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '4091045f974c'
down_revision: Union[str, Sequence[str], None] = 'fecc050b709e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adapter_certification_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('integration_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('passed_checks', sa.Integer(), nullable=False),
    sa.Column('total_checks', sa.Integer(), nullable=False),
    sa.Column('report_json', sa.Text(), nullable=False),
    sa.Column('report_hash', sa.String(length=64), nullable=False),
    sa.Column('executed_by_id', sa.String(length=36), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['executed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['integration_id'], ['provider_integrations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adapter_certification_runs_executed_at'), 'adapter_certification_runs', ['executed_at'], unique=False)
    op.create_index(op.f('ix_adapter_certification_runs_integration_id'), 'adapter_certification_runs', ['integration_id'], unique=False)
    op.create_index(op.f('ix_adapter_certification_runs_organization_id'), 'adapter_certification_runs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_adapter_certification_runs_report_hash'), 'adapter_certification_runs', ['report_hash'], unique=True)
    op.create_index(op.f('ix_adapter_certification_runs_status'), 'adapter_certification_runs', ['status'], unique=False)
    op.create_table('provider_go_live_approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('integration_id', sa.String(length=36), nullable=False),
    sa.Column('area', sa.String(length=30), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=False),
    sa.Column('decided_by_id', sa.String(length=36), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['integration_id'], ['provider_integrations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_id', 'area')
    )
    op.create_index(op.f('ix_provider_go_live_approvals_area'), 'provider_go_live_approvals', ['area'], unique=False)
    op.create_index(op.f('ix_provider_go_live_approvals_decided_at'), 'provider_go_live_approvals', ['decided_at'], unique=False)
    op.create_index(op.f('ix_provider_go_live_approvals_decision'), 'provider_go_live_approvals', ['decision'], unique=False)
    op.create_index(op.f('ix_provider_go_live_approvals_integration_id'), 'provider_go_live_approvals', ['integration_id'], unique=False)
    op.create_index(op.f('ix_provider_go_live_approvals_organization_id'), 'provider_go_live_approvals', ['organization_id'], unique=False)
    op.create_table('provider_go_live_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('integration_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('blockers_json', sa.Text(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('decided_by_id', sa.String(length=36), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['integration_id'], ['provider_integrations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_go_live_decisions_decided_at'), 'provider_go_live_decisions', ['decided_at'], unique=False)
    op.create_index(op.f('ix_provider_go_live_decisions_integration_id'), 'provider_go_live_decisions', ['integration_id'], unique=False)
    op.create_index(op.f('ix_provider_go_live_decisions_organization_id'), 'provider_go_live_decisions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_provider_go_live_decisions_snapshot_hash'), 'provider_go_live_decisions', ['snapshot_hash'], unique=True)
    op.create_index(op.f('ix_provider_go_live_decisions_status'), 'provider_go_live_decisions', ['status'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_go_live_decisions_status'), table_name='provider_go_live_decisions')
    op.drop_index(op.f('ix_provider_go_live_decisions_snapshot_hash'), table_name='provider_go_live_decisions')
    op.drop_index(op.f('ix_provider_go_live_decisions_organization_id'), table_name='provider_go_live_decisions')
    op.drop_index(op.f('ix_provider_go_live_decisions_integration_id'), table_name='provider_go_live_decisions')
    op.drop_index(op.f('ix_provider_go_live_decisions_decided_at'), table_name='provider_go_live_decisions')
    op.drop_table('provider_go_live_decisions')
    op.drop_index(op.f('ix_provider_go_live_approvals_organization_id'), table_name='provider_go_live_approvals')
    op.drop_index(op.f('ix_provider_go_live_approvals_integration_id'), table_name='provider_go_live_approvals')
    op.drop_index(op.f('ix_provider_go_live_approvals_decision'), table_name='provider_go_live_approvals')
    op.drop_index(op.f('ix_provider_go_live_approvals_decided_at'), table_name='provider_go_live_approvals')
    op.drop_index(op.f('ix_provider_go_live_approvals_area'), table_name='provider_go_live_approvals')
    op.drop_table('provider_go_live_approvals')
    op.drop_index(op.f('ix_adapter_certification_runs_status'), table_name='adapter_certification_runs')
    op.drop_index(op.f('ix_adapter_certification_runs_report_hash'), table_name='adapter_certification_runs')
    op.drop_index(op.f('ix_adapter_certification_runs_organization_id'), table_name='adapter_certification_runs')
    op.drop_index(op.f('ix_adapter_certification_runs_integration_id'), table_name='adapter_certification_runs')
    op.drop_index(op.f('ix_adapter_certification_runs_executed_at'), table_name='adapter_certification_runs')
    op.drop_table('adapter_certification_runs')
    # ### end Alembic commands ###
