"""billing collections and reconciliation

Revision ID: 5fad076ca8c4
Revises: f105a5a9a35a
Create Date: 2026-08-02 21:36:53.081011
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5fad076ca8c4'
down_revision: Union[str, Sequence[str], None] = 'f105a5a9a35a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('matched_records', sa.Integer(), nullable=False),
    sa.Column('divergent_records', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_index(op.f('ix_reconciliation_batches_organization_id'), 'reconciliation_batches', ['organization_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_batches_status'), 'reconciliation_batches', ['status'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('proposal_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_number', sa.String(length=80), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('interest_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'installment_number', 'kind')
    )
    op.create_index(op.f('ix_invoices_contract_id'), 'invoices', ['contract_id'], unique=False)
    op.create_index(op.f('ix_invoices_due_date'), 'invoices', ['due_date'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_organization_id'), 'invoices', ['organization_id'], unique=False)
    op.create_index(op.f('ix_invoices_proposal_id'), 'invoices', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('collection_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_actions_invoice_id'), 'collection_actions', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_collection_actions_organization_id'), 'collection_actions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_collection_actions_status'), 'collection_actions', ['status'], unique=False)
    op.create_table('delinquency_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('days_overdue', sa.Integer(), nullable=False),
    sa.Column('penalty_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('late_interest_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('caducity_eligible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delinquency_cases_invoice_id'), 'delinquency_cases', ['invoice_id'], unique=True)
    op.create_index(op.f('ix_delinquency_cases_organization_id'), 'delinquency_cases', ['organization_id'], unique=False)
    op.create_index(op.f('ix_delinquency_cases_status'), 'delinquency_cases', ['status'], unique=False)
    op.create_table('payment_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('provider_event_id', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_events_invoice_id'), 'payment_events', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payment_events_organization_id'), 'payment_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_payment_events_provider_event_id'), 'payment_events', ['provider_event_id'], unique=True)
    op.create_table('reconciliation_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=True),
    sa.Column('external_reference', sa.String(length=120), nullable=False),
    sa.Column('external_event_id', sa.String(length=120), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('received_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('resolved_by_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['reconciliation_batches.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_items_batch_id'), 'reconciliation_items', ['batch_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_items_external_reference'), 'reconciliation_items', ['external_reference'], unique=False)
    op.create_index(op.f('ix_reconciliation_items_invoice_id'), 'reconciliation_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_items_organization_id'), 'reconciliation_items', ['organization_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_items_status'), 'reconciliation_items', ['status'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliation_items_status'), table_name='reconciliation_items')
    op.drop_index(op.f('ix_reconciliation_items_organization_id'), table_name='reconciliation_items')
    op.drop_index(op.f('ix_reconciliation_items_invoice_id'), table_name='reconciliation_items')
    op.drop_index(op.f('ix_reconciliation_items_external_reference'), table_name='reconciliation_items')
    op.drop_index(op.f('ix_reconciliation_items_batch_id'), table_name='reconciliation_items')
    op.drop_table('reconciliation_items')
    op.drop_index(op.f('ix_payment_events_provider_event_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_organization_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_invoice_id'), table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index(op.f('ix_delinquency_cases_status'), table_name='delinquency_cases')
    op.drop_index(op.f('ix_delinquency_cases_organization_id'), table_name='delinquency_cases')
    op.drop_index(op.f('ix_delinquency_cases_invoice_id'), table_name='delinquency_cases')
    op.drop_table('delinquency_cases')
    op.drop_index(op.f('ix_collection_actions_status'), table_name='collection_actions')
    op.drop_index(op.f('ix_collection_actions_organization_id'), table_name='collection_actions')
    op.drop_index(op.f('ix_collection_actions_invoice_id'), table_name='collection_actions')
    op.drop_table('collection_actions')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_proposal_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_organization_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_due_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_contract_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_reconciliation_batches_status'), table_name='reconciliation_batches')
    op.drop_index(op.f('ix_reconciliation_batches_organization_id'), table_name='reconciliation_batches')
    op.drop_table('reconciliation_batches')
    # ### end Alembic commands ###
