"""provider onboarding vault mtls reconciliation evidence

Revision ID: 6bfa0e95f4d3
Revises: 0bf0b9a1af98
Create Date: 2026-08-03 16:40:04.506141
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '6bfa0e95f4d3'
down_revision: Union[str, Sequence[str], None] = '0bf0b9a1af98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secret_references',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('backend', sa.String(length=30), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=True),
    sa.Column('external_reference', sa.String(length=500), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_rotated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name')
    )
    op.create_index(op.f('ix_secret_references_name'), 'secret_references', ['name'], unique=False)
    op.create_index(op.f('ix_secret_references_organization_id'), 'secret_references', ['organization_id'], unique=False)
    op.create_table('integration_mtls_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('integration_id', sa.String(length=36), nullable=False),
    sa.Column('certificate_secret_id', sa.String(length=36), nullable=False),
    sa.Column('private_key_secret_id', sa.String(length=36), nullable=False),
    sa.Column('ca_secret_id', sa.String(length=36), nullable=True),
    sa.Column('verify_peer', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ca_secret_id'], ['secret_references.id'], ),
    sa.ForeignKeyConstraint(['certificate_secret_id'], ['secret_references.id'], ),
    sa.ForeignKeyConstraint(['integration_id'], ['provider_integrations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['private_key_secret_id'], ['secret_references.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_mtls_configs_integration_id'), 'integration_mtls_configs', ['integration_id'], unique=True)
    op.create_index(op.f('ix_integration_mtls_configs_organization_id'), 'integration_mtls_configs', ['organization_id'], unique=False)
    op.create_table('provider_onboarding_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('integration_id', sa.String(length=36), nullable=False),
    sa.Column('api_version', sa.String(length=40), nullable=False),
    sa.Column('authentication_type', sa.String(length=40), nullable=False),
    sa.Column('health_path', sa.String(length=200), nullable=False),
    sa.Column('reconciliation_mode', sa.String(length=30), nullable=False),
    sa.Column('checklist_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('homologated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['provider_integrations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_onboarding_profiles_integration_id'), 'provider_onboarding_profiles', ['integration_id'], unique=True)
    op.create_index(op.f('ix_provider_onboarding_profiles_organization_id'), 'provider_onboarding_profiles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_provider_onboarding_profiles_status'), 'provider_onboarding_profiles', ['status'], unique=False)
    op.create_table('provider_reconciliation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('integration_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_reference', sa.String(length=180), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('matched_items', sa.Integer(), nullable=False),
    sa.Column('divergent_items', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['provider_integrations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_reconciliation_runs_content_hash'), 'provider_reconciliation_runs', ['content_hash'], unique=True)
    op.create_index(op.f('ix_provider_reconciliation_runs_integration_id'), 'provider_reconciliation_runs', ['integration_id'], unique=False)
    op.create_index(op.f('ix_provider_reconciliation_runs_organization_id'), 'provider_reconciliation_runs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_provider_reconciliation_runs_source_type'), 'provider_reconciliation_runs', ['source_type'], unique=False)
    op.create_index(op.f('ix_provider_reconciliation_runs_status'), 'provider_reconciliation_runs', ['status'], unique=False)
    op.create_table('homologation_evidences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('integration_id', sa.String(length=36), nullable=False),
    sa.Column('control_key', sa.String(length=100), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=False),
    sa.Column('evidence_hash', sa.String(length=64), nullable=False),
    sa.Column('executed_by_id', sa.String(length=36), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['executed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['integration_id'], ['provider_integrations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_hash')
    )
    op.create_index(op.f('ix_homologation_evidences_control_key'), 'homologation_evidences', ['control_key'], unique=False)
    op.create_index(op.f('ix_homologation_evidences_executed_at'), 'homologation_evidences', ['executed_at'], unique=False)
    op.create_index(op.f('ix_homologation_evidences_integration_id'), 'homologation_evidences', ['integration_id'], unique=False)
    op.create_index(op.f('ix_homologation_evidences_organization_id'), 'homologation_evidences', ['organization_id'], unique=False)
    op.create_index(op.f('ix_homologation_evidences_result'), 'homologation_evidences', ['result'], unique=False)
    op.create_table('provider_reconciliation_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('provider_status', sa.String(length=50), nullable=False),
    sa.Column('match_status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['provider_reconciliation_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'external_id')
    )
    op.create_index(op.f('ix_provider_reconciliation_items_external_id'), 'provider_reconciliation_items', ['external_id'], unique=False)
    op.create_index(op.f('ix_provider_reconciliation_items_match_status'), 'provider_reconciliation_items', ['match_status'], unique=False)
    op.create_index(op.f('ix_provider_reconciliation_items_organization_id'), 'provider_reconciliation_items', ['organization_id'], unique=False)
    op.create_index(op.f('ix_provider_reconciliation_items_run_id'), 'provider_reconciliation_items', ['run_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_reconciliation_items_run_id'), table_name='provider_reconciliation_items')
    op.drop_index(op.f('ix_provider_reconciliation_items_organization_id'), table_name='provider_reconciliation_items')
    op.drop_index(op.f('ix_provider_reconciliation_items_match_status'), table_name='provider_reconciliation_items')
    op.drop_index(op.f('ix_provider_reconciliation_items_external_id'), table_name='provider_reconciliation_items')
    op.drop_table('provider_reconciliation_items')
    op.drop_index(op.f('ix_homologation_evidences_result'), table_name='homologation_evidences')
    op.drop_index(op.f('ix_homologation_evidences_organization_id'), table_name='homologation_evidences')
    op.drop_index(op.f('ix_homologation_evidences_integration_id'), table_name='homologation_evidences')
    op.drop_index(op.f('ix_homologation_evidences_executed_at'), table_name='homologation_evidences')
    op.drop_index(op.f('ix_homologation_evidences_control_key'), table_name='homologation_evidences')
    op.drop_table('homologation_evidences')
    op.drop_index(op.f('ix_provider_reconciliation_runs_status'), table_name='provider_reconciliation_runs')
    op.drop_index(op.f('ix_provider_reconciliation_runs_source_type'), table_name='provider_reconciliation_runs')
    op.drop_index(op.f('ix_provider_reconciliation_runs_organization_id'), table_name='provider_reconciliation_runs')
    op.drop_index(op.f('ix_provider_reconciliation_runs_integration_id'), table_name='provider_reconciliation_runs')
    op.drop_index(op.f('ix_provider_reconciliation_runs_content_hash'), table_name='provider_reconciliation_runs')
    op.drop_table('provider_reconciliation_runs')
    op.drop_index(op.f('ix_provider_onboarding_profiles_status'), table_name='provider_onboarding_profiles')
    op.drop_index(op.f('ix_provider_onboarding_profiles_organization_id'), table_name='provider_onboarding_profiles')
    op.drop_index(op.f('ix_provider_onboarding_profiles_integration_id'), table_name='provider_onboarding_profiles')
    op.drop_table('provider_onboarding_profiles')
    op.drop_index(op.f('ix_integration_mtls_configs_organization_id'), table_name='integration_mtls_configs')
    op.drop_index(op.f('ix_integration_mtls_configs_integration_id'), table_name='integration_mtls_configs')
    op.drop_table('integration_mtls_configs')
    op.drop_index(op.f('ix_secret_references_organization_id'), table_name='secret_references')
    op.drop_index(op.f('ix_secret_references_name'), table_name='secret_references')
    op.drop_table('secret_references')
    # ### end Alembic commands ###
