"""flash credit routing, valid stamp and lss

Revision ID: 83d4e5f6a7b8
Revises: 72c3d4e5f6a7
"""
from alembic import op
import sqlalchemy as sa
revision='83d4e5f6a7b8';down_revision='72c3d4e5f6a7';branch_labels=None;depends_on=None

def upgrade():
    op.create_table('flash_credit_policies',sa.Column('id',sa.String(36),primary_key=True),sa.Column('organization_id',sa.String(36),sa.ForeignKey('organizations.id'),nullable=False),sa.Column('version',sa.Integer(),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('max_ltv_percent',sa.Numeric(8,4),nullable=False),sa.Column('institutional_rate_annual',sa.Numeric(8,4),nullable=False),sa.Column('retail_rate_monthly',sa.Numeric(8,4),nullable=False),sa.Column('investor_rate_monthly',sa.Numeric(8,4),nullable=False),sa.Column('treasury_spread_monthly',sa.Numeric(8,4),nullable=False),sa.Column('auction_steps_json',sa.Text(),nullable=False),sa.Column('auction_floor_percent',sa.Numeric(8,4),nullable=False),sa.Column('intermediation_fee_percent',sa.Numeric(8,4),nullable=False),sa.Column('approved_by_id',sa.String(36),sa.ForeignKey('users.id')),sa.Column('approved_at',sa.DateTime(timezone=True)),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('organization_id','version'))
    op.create_index('ix_flash_credit_policies_organization_id','flash_credit_policies',['organization_id']);op.create_index('ix_flash_credit_policies_status','flash_credit_policies',['status'])
    op.create_table('flash_credit_parties',sa.Column('id',sa.String(36),primary_key=True),sa.Column('organization_id',sa.String(36),sa.ForeignKey('organizations.id'),nullable=False),sa.Column('proposal_id',sa.String(36),sa.ForeignKey('proposals.id'),nullable=False),sa.Column('party_role',sa.String(40),nullable=False),sa.Column('person_type',sa.String(10),nullable=False),sa.Column('document_masked',sa.String(30),nullable=False),sa.Column('legal_representative_document_masked',sa.String(30)),sa.Column('qsa_match_status',sa.String(30),nullable=False),sa.Column('liveness_reference',sa.String(200)),sa.Column('consent_status',sa.String(30),nullable=False),sa.Column('consent_hash',sa.String(64)),sa.Column('status',sa.String(30),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('proposal_id','party_role'))
    for n in ('organization_id','proposal_id','party_role','status'):op.create_index(f'ix_flash_credit_parties_{n}','flash_credit_parties',[n])
    op.create_table('valid_stamps',sa.Column('id',sa.String(36),primary_key=True),sa.Column('organization_id',sa.String(36),sa.ForeignKey('organizations.id'),nullable=False),sa.Column('stamp_code',sa.String(80),nullable=False),sa.Column('entity_type',sa.String(60),nullable=False),sa.Column('entity_id',sa.String(36),nullable=False),sa.Column('purpose',sa.String(80),nullable=False),sa.Column('algorithm',sa.String(30),nullable=False),sa.Column('payload_hash',sa.String(64),nullable=False),sa.Column('previous_hash',sa.String(64)),sa.Column('chain_hash',sa.String(64),nullable=False),sa.Column('signature',sa.String(64),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('issued_by_id',sa.String(36),sa.ForeignKey('users.id'),nullable=False),sa.Column('issued_at',sa.DateTime(timezone=True),nullable=False),sa.Column('revoked_at',sa.DateTime(timezone=True)),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('organization_id','stamp_code'),sa.UniqueConstraint('organization_id','entity_type','entity_id','purpose'),sa.UniqueConstraint('chain_hash'))
    for n in ('organization_id','stamp_code','entity_type','entity_id','chain_hash','status','issued_at'):op.create_index(f'ix_valid_stamps_{n}','valid_stamps',[n],unique=n=='chain_hash')
    op.create_table('saas_terms_templates',sa.Column('id',sa.String(36),primary_key=True),sa.Column('organization_id',sa.String(36),sa.ForeignKey('organizations.id'),nullable=False),sa.Column('code',sa.String(80),nullable=False),sa.Column('version',sa.Integer(),nullable=False),sa.Column('title',sa.String(200),nullable=False),sa.Column('body',sa.Text(),nullable=False),sa.Column('body_hash',sa.String(64),nullable=False),sa.Column('legal_review_status',sa.String(30),nullable=False),sa.Column('active',sa.Boolean(),nullable=False),sa.Column('approved_by_id',sa.String(36),sa.ForeignKey('users.id')),sa.Column('approved_at',sa.DateTime(timezone=True)),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('organization_id','code','version'))
    op.create_index('ix_saas_terms_templates_organization_id','saas_terms_templates',['organization_id']);op.create_index('ix_saas_terms_templates_code','saas_terms_templates',['code'])
    op.create_table('saas_plans',sa.Column('id',sa.String(36),primary_key=True),sa.Column('organization_id',sa.String(36),sa.ForeignKey('organizations.id'),nullable=False),sa.Column('code',sa.String(60),nullable=False),sa.Column('name',sa.String(160),nullable=False),sa.Column('monthly_price',sa.Numeric(15,2),nullable=False),sa.Column('central_share_percent',sa.Numeric(8,4),nullable=False),sa.Column('network_pool_percent',sa.Numeric(8,4),nullable=False),sa.Column('active',sa.Boolean(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('organization_id','code'))
    op.create_index('ix_saas_plans_organization_id','saas_plans',['organization_id']);op.create_index('ix_saas_plans_code','saas_plans',['code'])
    op.create_table('saas_subscriptions',sa.Column('id',sa.String(36),primary_key=True),sa.Column('organization_id',sa.String(36),sa.ForeignKey('organizations.id'),nullable=False),sa.Column('plan_id',sa.String(36),sa.ForeignKey('saas_plans.id'),nullable=False),sa.Column('terms_template_id',sa.String(36),sa.ForeignKey('saas_terms_templates.id'),nullable=False),sa.Column('subscriber_company_name',sa.String(180),nullable=False),sa.Column('subscriber_document_masked',sa.String(30),nullable=False),sa.Column('legal_representative_name',sa.String(180),nullable=False),sa.Column('legal_representative_document_masked',sa.String(30),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('current_period_start',sa.DateTime(timezone=True),nullable=False),sa.Column('current_period_end',sa.DateTime(timezone=True),nullable=False),sa.Column('cancel_at_period_end',sa.Boolean(),nullable=False),sa.Column('cancelled_at',sa.DateTime(timezone=True)),sa.Column('payment_method_reference',sa.String(200)),sa.Column('recurring_authorized',sa.Boolean(),nullable=False),sa.Column('acceptance_hash',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False))
    for n in ('organization_id','plan_id','status'):op.create_index(f'ix_saas_subscriptions_{n}','saas_subscriptions',[n])
    op.create_table('saas_acceptances',sa.Column('id',sa.String(36),primary_key=True),sa.Column('organization_id',sa.String(36),sa.ForeignKey('organizations.id'),nullable=False),sa.Column('subscription_id',sa.String(36),sa.ForeignKey('saas_subscriptions.id'),nullable=False),sa.Column('user_id',sa.String(36),sa.ForeignKey('users.id'),nullable=False),sa.Column('terms_template_id',sa.String(36),sa.ForeignKey('saas_terms_templates.id'),nullable=False),sa.Column('ip_address',sa.String(64)),sa.Column('user_agent',sa.String(500)),sa.Column('verification_reference',sa.String(200),nullable=False),sa.Column('evidence_json',sa.Text(),nullable=False),sa.Column('evidence_hash',sa.String(64),nullable=False),sa.Column('accepted_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('subscription_id'),sa.UniqueConstraint('evidence_hash'))
    op.create_index('ix_saas_acceptances_organization_id','saas_acceptances',['organization_id']);op.create_index('ix_saas_acceptances_subscription_id','saas_acceptances',['subscription_id'],unique=True);op.create_index('ix_saas_acceptances_evidence_hash','saas_acceptances',['evidence_hash'],unique=True)

def downgrade():
    for t in ('saas_acceptances','saas_subscriptions','saas_plans','saas_terms_templates','valid_stamps','flash_credit_parties','flash_credit_policies'):op.drop_table(t)
