"""nina underwriting and business intelligence

Revision ID: 936cb7ecfcda
Revises: 09c4acc8ee4e
Create Date: 2026-08-03 15:34:22.787469
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '936cb7ecfcda'
down_revision: Union[str, Sequence[str], None] = '09c4acc8ee4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('underwriting_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('product', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('minimum_score', sa.Integer(), nullable=False),
    sa.Column('maximum_ltv_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('maximum_commitment_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('manual_review_score', sa.Integer(), nullable=False),
    sa.Column('rules_json', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'product', 'version')
    )
    op.create_index(op.f('ix_underwriting_policies_organization_id'), 'underwriting_policies', ['organization_id'], unique=False)
    op.create_index(op.f('ix_underwriting_policies_product'), 'underwriting_policies', ['product'], unique=False)
    op.create_table('underwriting_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('proposal_id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('risk_band', sa.String(length=20), nullable=False),
    sa.Column('recommendation', sa.String(length=30), nullable=False),
    sa.Column('inputs_json', sa.Text(), nullable=False),
    sa.Column('explanation_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assessed_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['underwriting_policies.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id', 'version')
    )
    op.create_index(op.f('ix_underwriting_assessments_organization_id'), 'underwriting_assessments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_underwriting_assessments_policy_id'), 'underwriting_assessments', ['policy_id'], unique=False)
    op.create_index(op.f('ix_underwriting_assessments_proposal_id'), 'underwriting_assessments', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_underwriting_assessments_recommendation'), 'underwriting_assessments', ['recommendation'], unique=False)
    op.create_index(op.f('ix_underwriting_assessments_risk_band'), 'underwriting_assessments', ['risk_band'], unique=False)
    op.create_index(op.f('ix_underwriting_assessments_score'), 'underwriting_assessments', ['score'], unique=False)
    op.create_index(op.f('ix_underwriting_assessments_status'), 'underwriting_assessments', ['status'], unique=False)
    op.create_table('underwriting_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('decided_by_id', sa.String(length=36), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['underwriting_assessments.id'], ),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    op.create_index(op.f('ix_underwriting_decisions_assessment_id'), 'underwriting_decisions', ['assessment_id'], unique=True)
    op.create_index(op.f('ix_underwriting_decisions_decision'), 'underwriting_decisions', ['decision'], unique=False)
    op.create_index(op.f('ix_underwriting_decisions_organization_id'), 'underwriting_decisions', ['organization_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_underwriting_decisions_organization_id'), table_name='underwriting_decisions')
    op.drop_index(op.f('ix_underwriting_decisions_decision'), table_name='underwriting_decisions')
    op.drop_index(op.f('ix_underwriting_decisions_assessment_id'), table_name='underwriting_decisions')
    op.drop_table('underwriting_decisions')
    op.drop_index(op.f('ix_underwriting_assessments_status'), table_name='underwriting_assessments')
    op.drop_index(op.f('ix_underwriting_assessments_score'), table_name='underwriting_assessments')
    op.drop_index(op.f('ix_underwriting_assessments_risk_band'), table_name='underwriting_assessments')
    op.drop_index(op.f('ix_underwriting_assessments_recommendation'), table_name='underwriting_assessments')
    op.drop_index(op.f('ix_underwriting_assessments_proposal_id'), table_name='underwriting_assessments')
    op.drop_index(op.f('ix_underwriting_assessments_policy_id'), table_name='underwriting_assessments')
    op.drop_index(op.f('ix_underwriting_assessments_organization_id'), table_name='underwriting_assessments')
    op.drop_table('underwriting_assessments')
    op.drop_index(op.f('ix_underwriting_policies_product'), table_name='underwriting_policies')
    op.drop_index(op.f('ix_underwriting_policies_organization_id'), table_name='underwriting_policies')
    op.drop_table('underwriting_policies')
    # ### end Alembic commands ###
