"""resilient provider integrations and signed webhooks

Revision ID: 99dae05d6519
Revises: 08c10ac5905c
Create Date: 2026-08-03 16:16:57.950378
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '99dae05d6519'
down_revision: Union[str, Sequence[str], None] = '08c10ac5905c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_integrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('credential_ciphertext', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('health_status', sa.String(length=30), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('last_health_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('circuit_status', sa.String(length=20), nullable=False),
    sa.Column('circuit_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'provider', 'environment')
    )
    op.create_index(op.f('ix_provider_integrations_category'), 'provider_integrations', ['category'], unique=False)
    op.create_index(op.f('ix_provider_integrations_circuit_status'), 'provider_integrations', ['circuit_status'], unique=False)
    op.create_index(op.f('ix_provider_integrations_environment'), 'provider_integrations', ['environment'], unique=False)
    op.create_index(op.f('ix_provider_integrations_health_status'), 'provider_integrations', ['health_status'], unique=False)
    op.create_index(op.f('ix_provider_integrations_organization_id'), 'provider_integrations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_provider_integrations_provider'), 'provider_integrations', ['provider'], unique=False)
    op.create_table('webhook_endpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('integration_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('target_url', sa.String(length=500), nullable=False),
    sa.Column('secret_ciphertext', sa.Text(), nullable=False),
    sa.Column('subscribed_events_json', sa.Text(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['provider_integrations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name')
    )
    op.create_index(op.f('ix_webhook_endpoints_integration_id'), 'webhook_endpoints', ['integration_id'], unique=False)
    op.create_index(op.f('ix_webhook_endpoints_name'), 'webhook_endpoints', ['name'], unique=False)
    op.create_index(op.f('ix_webhook_endpoints_organization_id'), 'webhook_endpoints', ['organization_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('endpoint_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('signature', sa.String(length=180), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.String(length=500), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint_id', 'event_id')
    )
    op.create_index(op.f('ix_webhook_deliveries_endpoint_id'), 'webhook_deliveries', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_event_id'), 'webhook_deliveries', ['event_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_event_type'), 'webhook_deliveries', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_next_attempt_at'), 'webhook_deliveries', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_organization_id'), 'webhook_deliveries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_status'), 'webhook_deliveries', ['status'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_deliveries_status'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_organization_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_next_attempt_at'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_event_type'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_event_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_endpoint_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_webhook_endpoints_organization_id'), table_name='webhook_endpoints')
    op.drop_index(op.f('ix_webhook_endpoints_name'), table_name='webhook_endpoints')
    op.drop_index(op.f('ix_webhook_endpoints_integration_id'), table_name='webhook_endpoints')
    op.drop_table('webhook_endpoints')
    op.drop_index(op.f('ix_provider_integrations_provider'), table_name='provider_integrations')
    op.drop_index(op.f('ix_provider_integrations_organization_id'), table_name='provider_integrations')
    op.drop_index(op.f('ix_provider_integrations_health_status'), table_name='provider_integrations')
    op.drop_index(op.f('ix_provider_integrations_environment'), table_name='provider_integrations')
    op.drop_index(op.f('ix_provider_integrations_circuit_status'), table_name='provider_integrations')
    op.drop_index(op.f('ix_provider_integrations_category'), table_name='provider_integrations')
    op.drop_table('provider_integrations')
    # ### end Alembic commands ###
