"""auctions and asset recovery

Revision ID: a2c0a1af2b4e
Revises: 5fad076ca8c4
Create Date: 2026-08-02 21:43:50.523462
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a2c0a1af2b4e'
down_revision: Union[str, Sequence[str], None] = '5fad076ca8c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovered_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('delinquency_case_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('asset_type', sa.String(length=40), nullable=False),
    sa.Column('public_description', sa.Text(), nullable=False),
    sa.Column('gated_details_json', sa.Text(), nullable=False),
    sa.Column('appraisal_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('debt_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('recovery_costs', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('custody_reference', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['delinquency_case_id'], ['delinquency_cases.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custody_reference')
    )
    op.create_index(op.f('ix_recovered_assets_delinquency_case_id'), 'recovered_assets', ['delinquency_case_id'], unique=False)
    op.create_index(op.f('ix_recovered_assets_organization_id'), 'recovered_assets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_recovered_assets_status'), 'recovered_assets', ['status'], unique=False)
    op.create_table('auction_lots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('lot_number', sa.String(length=60), nullable=False),
    sa.Column('opening_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('reserve_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('min_increment', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('platform_fee_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extension_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('winning_bid_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['recovered_assets.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auction_lots_asset_id'), 'auction_lots', ['asset_id'], unique=True)
    op.create_index(op.f('ix_auction_lots_ends_at'), 'auction_lots', ['ends_at'], unique=False)
    op.create_index(op.f('ix_auction_lots_lot_number'), 'auction_lots', ['lot_number'], unique=True)
    op.create_index(op.f('ix_auction_lots_organization_id'), 'auction_lots', ['organization_id'], unique=False)
    op.create_index(op.f('ix_auction_lots_starts_at'), 'auction_lots', ['starts_at'], unique=False)
    op.create_index(op.f('ix_auction_lots_status'), 'auction_lots', ['status'], unique=False)
    op.create_table('auction_bids',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('lot_id', sa.String(length=36), nullable=False),
    sa.Column('bidder_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bidder_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['auction_lots.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auction_bids_bidder_id'), 'auction_bids', ['bidder_id'], unique=False)
    op.create_index(op.f('ix_auction_bids_idempotency_key'), 'auction_bids', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_auction_bids_lot_id'), 'auction_bids', ['lot_id'], unique=False)
    op.create_index(op.f('ix_auction_bids_organization_id'), 'auction_bids', ['organization_id'], unique=False)
    op.create_index(op.f('ix_auction_bids_placed_at'), 'auction_bids', ['placed_at'], unique=False)
    op.create_index(op.f('ix_auction_bids_status'), 'auction_bids', ['status'], unique=False)
    op.create_table('auction_qualifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('lot_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('terms_version', sa.String(length=30), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['auction_lots.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_id', 'user_id')
    )
    op.create_index(op.f('ix_auction_qualifications_lot_id'), 'auction_qualifications', ['lot_id'], unique=False)
    op.create_index(op.f('ix_auction_qualifications_organization_id'), 'auction_qualifications', ['organization_id'], unique=False)
    op.create_index(op.f('ix_auction_qualifications_status'), 'auction_qualifications', ['status'], unique=False)
    op.create_index(op.f('ix_auction_qualifications_user_id'), 'auction_qualifications', ['user_id'], unique=False)
    op.create_table('auction_settlements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('lot_id', sa.String(length=36), nullable=False),
    sa.Column('winning_bid_id', sa.String(length=36), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('recovery_costs', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('debt_paid', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('owner_surplus', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['auction_lots.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['winning_bid_id'], ['auction_bids.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('winning_bid_id')
    )
    op.create_index(op.f('ix_auction_settlements_lot_id'), 'auction_settlements', ['lot_id'], unique=True)
    op.create_index(op.f('ix_auction_settlements_organization_id'), 'auction_settlements', ['organization_id'], unique=False)
    op.create_index(op.f('ix_auction_settlements_status'), 'auction_settlements', ['status'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auction_settlements_status'), table_name='auction_settlements')
    op.drop_index(op.f('ix_auction_settlements_organization_id'), table_name='auction_settlements')
    op.drop_index(op.f('ix_auction_settlements_lot_id'), table_name='auction_settlements')
    op.drop_table('auction_settlements')
    op.drop_index(op.f('ix_auction_qualifications_user_id'), table_name='auction_qualifications')
    op.drop_index(op.f('ix_auction_qualifications_status'), table_name='auction_qualifications')
    op.drop_index(op.f('ix_auction_qualifications_organization_id'), table_name='auction_qualifications')
    op.drop_index(op.f('ix_auction_qualifications_lot_id'), table_name='auction_qualifications')
    op.drop_table('auction_qualifications')
    op.drop_index(op.f('ix_auction_bids_status'), table_name='auction_bids')
    op.drop_index(op.f('ix_auction_bids_placed_at'), table_name='auction_bids')
    op.drop_index(op.f('ix_auction_bids_organization_id'), table_name='auction_bids')
    op.drop_index(op.f('ix_auction_bids_lot_id'), table_name='auction_bids')
    op.drop_index(op.f('ix_auction_bids_idempotency_key'), table_name='auction_bids')
    op.drop_index(op.f('ix_auction_bids_bidder_id'), table_name='auction_bids')
    op.drop_table('auction_bids')
    op.drop_index(op.f('ix_auction_lots_status'), table_name='auction_lots')
    op.drop_index(op.f('ix_auction_lots_starts_at'), table_name='auction_lots')
    op.drop_index(op.f('ix_auction_lots_organization_id'), table_name='auction_lots')
    op.drop_index(op.f('ix_auction_lots_lot_number'), table_name='auction_lots')
    op.drop_index(op.f('ix_auction_lots_ends_at'), table_name='auction_lots')
    op.drop_index(op.f('ix_auction_lots_asset_id'), table_name='auction_lots')
    op.drop_table('auction_lots')
    op.drop_index(op.f('ix_recovered_assets_status'), table_name='recovered_assets')
    op.drop_index(op.f('ix_recovered_assets_organization_id'), table_name='recovered_assets')
    op.drop_index(op.f('ix_recovered_assets_delinquency_case_id'), table_name='recovered_assets')
    op.drop_table('recovered_assets')
    # ### end Alembic commands ###
