"""operational hardening and durable jobs

Revision ID: bfb261a2e10f
Revises: 936cb7ecfcda
Create Date: 2026-08-03 15:49:51.056669
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'bfb261a2e10f'
down_revision: Union[str, Sequence[str], None] = '936cb7ecfcda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operational_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operational_jobs_idempotency_key'), 'operational_jobs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_operational_jobs_job_type'), 'operational_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_operational_jobs_organization_id'), 'operational_jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_operational_jobs_scheduled_at'), 'operational_jobs', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_operational_jobs_status'), 'operational_jobs', ['status'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operational_jobs_status'), table_name='operational_jobs')
    op.drop_index(op.f('ix_operational_jobs_scheduled_at'), table_name='operational_jobs')
    op.drop_index(op.f('ix_operational_jobs_organization_id'), table_name='operational_jobs')
    op.drop_index(op.f('ix_operational_jobs_job_type'), table_name='operational_jobs')
    op.drop_index(op.f('ix_operational_jobs_idempotency_key'), table_name='operational_jobs')
    op.drop_table('operational_jobs')
    # ### end Alembic commands ###
