"""documents escrow signatures and payouts

Revision ID: c781263d6e62
Revises: bd6be07f83ee
Create Date: 2026-08-02 20:46:24.026480
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c781263d6e62'
down_revision: Union[str, Sequence[str], None] = 'bd6be07f83ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('normal_balance', sa.String(length=10), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code')
    )
    op.create_index(op.f('ix_chart_accounts_organization_id'), 'chart_accounts', ['organization_id'], unique=False)
    op.create_table('escrow_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('operation_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('external_account_id', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('locked_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_account_id'),
    sa.UniqueConstraint('operation_id')
    )
    op.create_index(op.f('ix_escrow_accounts_organization_id'), 'escrow_accounts', ['organization_id'], unique=False)
    op.create_table('escrow_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('escrow_account_id', sa.String(length=36), nullable=False),
    sa.Column('provider_event_id', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['escrow_account_id'], ['escrow_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escrow_events_escrow_account_id'), 'escrow_events', ['escrow_account_id'], unique=False)
    op.create_index(op.f('ix_escrow_events_organization_id'), 'escrow_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_escrow_events_provider_event_id'), 'escrow_events', ['provider_event_id'], unique=True)
    op.create_table('payout_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('escrow_account_id', sa.String(length=36), nullable=False),
    sa.Column('requested_by_id', sa.String(length=36), nullable=False),
    sa.Column('beneficiary_name', sa.String(length=180), nullable=False),
    sa.Column('beneficiary_document', sa.String(length=20), nullable=False),
    sa.Column('pix_key_masked', sa.String(length=180), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('condition_evidence_json', sa.Text(), nullable=False),
    sa.Column('provider_transaction_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['escrow_account_id'], ['escrow_accounts.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payout_requests_escrow_account_id'), 'payout_requests', ['escrow_account_id'], unique=False)
    op.create_index(op.f('ix_payout_requests_organization_id'), 'payout_requests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_payout_requests_status'), 'payout_requests', ['status'], unique=False)
    op.create_table('signature_envelopes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('signer_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_signature_envelopes_organization_id'), 'signature_envelopes', ['organization_id'], unique=False)
    op.create_table('payout_approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('payout_request_id', sa.String(length=36), nullable=False),
    sa.Column('approver_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payout_request_id'], ['payout_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payout_request_id', 'approver_id')
    )
    op.create_index(op.f('ix_payout_approvals_payout_request_id'), 'payout_approvals', ['payout_request_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payout_approvals_payout_request_id'), table_name='payout_approvals')
    op.drop_table('payout_approvals')
    op.drop_index(op.f('ix_signature_envelopes_organization_id'), table_name='signature_envelopes')
    op.drop_table('signature_envelopes')
    op.drop_index(op.f('ix_payout_requests_status'), table_name='payout_requests')
    op.drop_index(op.f('ix_payout_requests_organization_id'), table_name='payout_requests')
    op.drop_index(op.f('ix_payout_requests_escrow_account_id'), table_name='payout_requests')
    op.drop_table('payout_requests')
    op.drop_index(op.f('ix_escrow_events_provider_event_id'), table_name='escrow_events')
    op.drop_index(op.f('ix_escrow_events_organization_id'), table_name='escrow_events')
    op.drop_index(op.f('ix_escrow_events_escrow_account_id'), table_name='escrow_events')
    op.drop_table('escrow_events')
    op.drop_index(op.f('ix_escrow_accounts_organization_id'), table_name='escrow_accounts')
    op.drop_table('escrow_accounts')
    op.drop_index(op.f('ix_chart_accounts_organization_id'), table_name='chart_accounts')
    op.drop_table('chart_accounts')
    # ### end Alembic commands ###
