"""mmn commissions and funding

Revision ID: f105a5a9a35a
Revises: 6fea83aee5dc
Create Date: 2026-08-02 21:24:04.175773
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f105a5a9a35a'
down_revision: Union[str, Sequence[str], None] = '6fea83aee5dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('product', sa.String(length=50), nullable=False),
    sa.Column('commission_type', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('base_type', sa.String(length=40), nullable=False),
    sa.Column('pool_rate_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('levels_json', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'product', 'commission_type', 'version')
    )
    op.create_index(op.f('ix_commission_rules_organization_id'), 'commission_rules', ['organization_id'], unique=False)
    op.create_index(op.f('ix_commission_rules_product'), 'commission_rules', ['product'], unique=False)
    op.create_table('fiscal_evidences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('reference_month', sa.String(length=7), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('document_hash', sa.String(length=64), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_hash')
    )
    op.create_index(op.f('ix_fiscal_evidences_organization_id'), 'fiscal_evidences', ['organization_id'], unique=False)
    op.create_index(op.f('ix_fiscal_evidences_user_id'), 'fiscal_evidences', ['user_id'], unique=False)
    op.create_table('network_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('sponsor_user_id', sa.String(length=36), nullable=True),
    sa.Column('tree_type', sa.String(length=20), nullable=False),
    sa.Column('referral_code', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['sponsor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', 'tree_type')
    )
    op.create_index(op.f('ix_network_nodes_organization_id'), 'network_nodes', ['organization_id'], unique=False)
    op.create_index(op.f('ix_network_nodes_referral_code'), 'network_nodes', ['referral_code'], unique=True)
    op.create_index(op.f('ix_network_nodes_sponsor_user_id'), 'network_nodes', ['sponsor_user_id'], unique=False)
    op.create_index(op.f('ix_network_nodes_user_id'), 'network_nodes', ['user_id'], unique=False)
    op.create_table('commission_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('beneficiary_id', sa.String(length=36), nullable=False),
    sa.Column('originator_id', sa.String(length=36), nullable=False),
    sa.Column('proposal_id', sa.String(length=36), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=False),
    sa.Column('product', sa.String(length=50), nullable=False),
    sa.Column('commission_type', sa.String(length=20), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('calculation_base', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('pool_rate_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('level_share_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['originator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference', 'beneficiary_id', 'commission_type', 'level')
    )
    op.create_index(op.f('ix_commission_entries_beneficiary_id'), 'commission_entries', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_commission_entries_organization_id'), 'commission_entries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_commission_entries_originator_id'), 'commission_entries', ['originator_id'], unique=False)
    op.create_index(op.f('ix_commission_entries_proposal_id'), 'commission_entries', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_commission_entries_reference'), 'commission_entries', ['reference'], unique=False)
    op.create_index(op.f('ix_commission_entries_status'), 'commission_entries', ['status'], unique=False)
    op.create_table('funding_opportunities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('proposal_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('product', sa.String(length=50), nullable=False),
    sa.Column('capital_source', sa.String(length=30), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('funded_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('min_investment', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('annual_return_reference', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_opportunities_organization_id'), 'funding_opportunities', ['organization_id'], unique=False)
    op.create_index(op.f('ix_funding_opportunities_proposal_id'), 'funding_opportunities', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_funding_opportunities_status'), 'funding_opportunities', ['status'], unique=False)
    op.create_table('investment_positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('investor_id', sa.String(length=36), nullable=False),
    sa.Column('principal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('accrued_return', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['funding_opportunities.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'investor_id')
    )
    op.create_index(op.f('ix_investment_positions_investor_id'), 'investment_positions', ['investor_id'], unique=False)
    op.create_index(op.f('ix_investment_positions_opportunity_id'), 'investment_positions', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_investment_positions_organization_id'), 'investment_positions', ['organization_id'], unique=False)
    op.create_table('investment_reservations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('investor_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['funding_opportunities.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'investor_id')
    )
    op.create_index(op.f('ix_investment_reservations_investor_id'), 'investment_reservations', ['investor_id'], unique=False)
    op.create_index(op.f('ix_investment_reservations_opportunity_id'), 'investment_reservations', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_investment_reservations_organization_id'), 'investment_reservations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_investment_reservations_status'), 'investment_reservations', ['status'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investment_reservations_status'), table_name='investment_reservations')
    op.drop_index(op.f('ix_investment_reservations_organization_id'), table_name='investment_reservations')
    op.drop_index(op.f('ix_investment_reservations_opportunity_id'), table_name='investment_reservations')
    op.drop_index(op.f('ix_investment_reservations_investor_id'), table_name='investment_reservations')
    op.drop_table('investment_reservations')
    op.drop_index(op.f('ix_investment_positions_organization_id'), table_name='investment_positions')
    op.drop_index(op.f('ix_investment_positions_opportunity_id'), table_name='investment_positions')
    op.drop_index(op.f('ix_investment_positions_investor_id'), table_name='investment_positions')
    op.drop_table('investment_positions')
    op.drop_index(op.f('ix_funding_opportunities_status'), table_name='funding_opportunities')
    op.drop_index(op.f('ix_funding_opportunities_proposal_id'), table_name='funding_opportunities')
    op.drop_index(op.f('ix_funding_opportunities_organization_id'), table_name='funding_opportunities')
    op.drop_table('funding_opportunities')
    op.drop_index(op.f('ix_commission_entries_status'), table_name='commission_entries')
    op.drop_index(op.f('ix_commission_entries_reference'), table_name='commission_entries')
    op.drop_index(op.f('ix_commission_entries_proposal_id'), table_name='commission_entries')
    op.drop_index(op.f('ix_commission_entries_originator_id'), table_name='commission_entries')
    op.drop_index(op.f('ix_commission_entries_organization_id'), table_name='commission_entries')
    op.drop_index(op.f('ix_commission_entries_beneficiary_id'), table_name='commission_entries')
    op.drop_table('commission_entries')
    op.drop_index(op.f('ix_network_nodes_user_id'), table_name='network_nodes')
    op.drop_index(op.f('ix_network_nodes_sponsor_user_id'), table_name='network_nodes')
    op.drop_index(op.f('ix_network_nodes_referral_code'), table_name='network_nodes')
    op.drop_index(op.f('ix_network_nodes_organization_id'), table_name='network_nodes')
    op.drop_table('network_nodes')
    op.drop_index(op.f('ix_fiscal_evidences_user_id'), table_name='fiscal_evidences')
    op.drop_index(op.f('ix_fiscal_evidences_organization_id'), table_name='fiscal_evidences')
    op.drop_table('fiscal_evidences')
    op.drop_index(op.f('ix_commission_rules_product'), table_name='commission_rules')
    op.drop_index(op.f('ix_commission_rules_organization_id'), table_name='commission_rules')
    op.drop_table('commission_rules')
    # ### end Alembic commands ###
