"""sandbox provider adapter registry and executions

Revision ID: fecc050b709e
Revises: 6bfa0e95f4d3
Create Date: 2026-08-03 16:52:35.683605
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'fecc050b709e'
down_revision: Union[str, Sequence[str], None] = '6bfa0e95f4d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adapter_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('integration_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('operation', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('adapter_name', sa.String(length=100), nullable=False),
    sa.Column('adapter_version', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['provider_integrations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_id', 'idempotency_key')
    )
    op.create_index(op.f('ix_adapter_executions_category'), 'adapter_executions', ['category'], unique=False)
    op.create_index(op.f('ix_adapter_executions_created_at'), 'adapter_executions', ['created_at'], unique=False)
    op.create_index(op.f('ix_adapter_executions_external_id'), 'adapter_executions', ['external_id'], unique=False)
    op.create_index(op.f('ix_adapter_executions_idempotency_key'), 'adapter_executions', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_adapter_executions_integration_id'), 'adapter_executions', ['integration_id'], unique=False)
    op.create_index(op.f('ix_adapter_executions_operation'), 'adapter_executions', ['operation'], unique=False)
    op.create_index(op.f('ix_adapter_executions_organization_id'), 'adapter_executions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_adapter_executions_status'), 'adapter_executions', ['status'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adapter_executions_status'), table_name='adapter_executions')
    op.drop_index(op.f('ix_adapter_executions_organization_id'), table_name='adapter_executions')
    op.drop_index(op.f('ix_adapter_executions_operation'), table_name='adapter_executions')
    op.drop_index(op.f('ix_adapter_executions_integration_id'), table_name='adapter_executions')
    op.drop_index(op.f('ix_adapter_executions_idempotency_key'), table_name='adapter_executions')
    op.drop_index(op.f('ix_adapter_executions_external_id'), table_name='adapter_executions')
    op.drop_index(op.f('ix_adapter_executions_created_at'), table_name='adapter_executions')
    op.drop_index(op.f('ix_adapter_executions_category'), table_name='adapter_executions')
    op.drop_table('adapter_executions')
    # ### end Alembic commands ###
